### ISSUE TITLE
Connecting to a remote Docker daemon and running arbitrary commands

### ISSUE THREAD

**Issue by RinaldoBuratti** [mariotoffia/FluentDocker#102]
Hi Mario,

I need to connect to a remote host where there is a docker container up and running, then I need to launch shell command inside of that container. There is a way I can do that with Fluent Docker? In case could you provide an example?

Thank you in advance,
Rinaldo

**Comment by mariotoffia** [comment]
How to connect to remote host and fire up a container is described in the `README.md` file (in the [remote chapter](https://github.com/mariotoffia/FluentDocker#connecting-to-remote-docker-daemons)). When you want to execute commands inside the container just use the methology described in Issue #99. If it do not work, please do not hesitate to re-open this issue again.

Cheers,
 Mario
