### ISSUE TITLE
ICompositeService object properties when using compose not flushed on Dispose()?

### ISSUE THREAD

**Issue by ahmed-umair** [mariotoffia/FluentDocker#103]
Hi,
I ran into a problem while using the Fluent API to start, stop and view the status of docker-compose based services using a compose file. 

While the API starts up and shuts down containers just fine according to the provided compose file, the ICompositeService object used to build, start and stop the service does not reflect the status of the containers accurately after Stop() and Dispose() are called on it. It still retains the list of containers and images after the calls. Moreover it shows the containers status as still running even though they have been successfully terminated by the Stop() call.

Some guidance with the issue would be appreciated :)

**Comment by mariotoffia** [comment]
Agreed that is ugly will fix it in next release - thanks for the bug report!

**Comment by ahmed-umair** [comment]
Thanks mate. Looking forward to it! And thank you for creating this library in the first place :)

**Comment by mariotoffia** [comment]
Will be part of next release.
