### ISSUE TITLE
Bug: BuildArguments format is incorrect

### ISSUE THREAD

**Issue by DonSupreme** [mariotoffia/FluentDocker#106]
The .BuildArgument(string[]) method does not work correctly. I suspect its due to a typo in Ductus.FluentDocker/Model/Containers/ContainerBuildParams.cs on line 180

Current Line 180 :
      sb.OptionIfExists("--build-arg=", BuildArguments);

Should be (replace = with a space):
      sb.OptionIfExists("--build-arg ", BuildArguments);

**Comment by mariotoffia** [comment]
Thanks for the bug report - I’ll wrap up a few fixes into a release where this will be fixed as well.

**Comment by mariotoffia** [comment]
@DonSupreme  - Fixed and will be release this weekend. Many thanks for the bug report!

**Comment by DonSupreme** [comment]
> @DonSupreme - Fixed and will be release this weekend. Many thanks for the bug report!

My pleasure, thanks for fixing it so quickly. I was also trying to branch and fix myself, but seemed I didn't have access to.

**Comment by mariotoffia** [comment]
@DonSupreme you need to fork into your repo and then submit pull request. I gladly accepts other PRs :)
