### ISSUE TITLE
Feature Request - Rendering Dockerfile 

### ISSUE THREAD

**Issue by ali-tayebi** [mariotoffia/FluentDocker#108]
**Feature Proposal**
Would be great to add a feature to render Dockerfile and docker-compose file.

**Use-case**
It provides generating and updating Dockerfiles using code. It helps to automate these tasks. Great for applying consistency to multiple project and services, e.g. microservices.

**Implementation**
Would be limited to FileBuilder with making the RenderDockerfile public. 
Also, RenderDockerfileAsString() can be added to facilitate automated testing.

 **Actions**
I am happy to raise the PR as soon as the maintainers have approved the proposal.

I couldn't find any documentation about contributing so I just raise it here

**Comment by mariotoffia** [comment]
That's a really good idea. I think a good approach would be to _"detach"_ the `FileBuilder` from the `ImageBuilder`. For example we could strip out all around `ImageBuilder` in the `FileBuilder` and create a subclass e.g. `ImageFileBuilder` where it's constructor is internal (where the `FileBuilder` constructor is public) and only handle image related in the derived class such as 
```cs
   public IContainerImageService Build()
    {
      return _parent.Build();
    }
```

Where the `FileBuilder` would build the docker string. Thus it will be possible to use the  `FileBuilder` without required to build a image of it directly. I will do the same with the docker-compose builder (I'm still in progress of creating all the models).

What do you think about that?

Cheers,
 Mario

**Comment by ali-tayebi** [comment]
It makes a perfect sense to me.

**Comment by mariotoffia** [comment]
fixed - will be released in next release.
