### ISSUE TITLE
Enhancement: WithHostName

### ISSUE THREAD

**Issue by DonSupreme** [mariotoffia/FluentDocker#110]
Please add WithHostName to API similar to the existing WithName.

**Comment by mariotoffia** [comment]
will do!

**Comment by mariotoffia** [comment]
@DonSupreme Sorry, I was way too quick. Where do you want this API and for what purpose? Can you please give it more context?

Cheers,
  Mario

**Comment by DonSupreme** [comment]
For example:

var myContainer = new Builder()
 .UseContainer()
 .UseImage("mycontainer:latest")
 .ReuseIfExists()
 .WithName("thebestcontainer")
 .WithHostName("thebestcontainer") ### Add it here
 .ExposePort(5672, 5672)
 .Build();

I need to set hostname when the container is run so that the container's netbios name is set to what I specify. Does this make sense?

**Comment by mariotoffia** [comment]
@DonSupreme  Added as you outlined above. It will be part of the next release.

Cheers,
 Mario
