### ISSUE TITLE
How to stop compose service without deleting container?

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [mariotoffia/FluentDocker#112]
FluentDocker `2.7.2`

TL;DR:
How to `Stop()` containers created by `...UseCompose()...Start()` **without removing them**?
As in `docker-compose stop` ?

Given this `testcase1.yml`:
```yaml
version: '2.1'
services:
  myservice:
    image: myimage
```

Executing this:
```csharp
// ax-docker02 is a linux centos host
Environment.SetEnvironmentVariable("DOCKER_HOST", "ax-docker02:2375");

var composition = new Builder()
                    .UseContainer().KeepContainer()
                    .UseCompose()
                    .FromFile("testcase1.yml")
                    .KeepOnDispose()
                    .Build();

composition.Start();
composition.Stop(); // Just stop, please?
```
will result in **the container `myservice` being deleted.**

I've added `KeepContainer()` and `KeepOnDispose()` only for trying, they have no effect on the `Stop()` it seems.

[EDIT] If one does **not call `Dispose`**, then this is an easy solution to stop all services (containers) defined in the `compose` file:
```csharp
composition.Containers.ToList().ForEach(c => c.Stop());
```
Thats fine with me, still curious for your answer :smiley:

Greetings

**Comment by mariotoffia** [comment]
Hi and thanks for the issue report.

I agree that the ```Stop``` should only stop the containers and not tear down and delete anything - **It is  a BUG**. 

In addition the ```Dispose``` method should stop (need to add a ```KeepContainer``` on the ```CompositeBuilder```) and dispose the containers (if not ```KeepOnDispose```) to make it adhere to same contract as the ```ContainerBuilder``` and the  ```ContainerService```.

Theese needs fixing.

As a final note, a  instance implementing the ```IDisposable``` **shall** always be disposed - if it cannot (as in this case) is a **BUG**. 

Cheers,
 Mario

**Comment by mariotoffia** [comment]
Closing this issue since, Issue #113 is tracking the complete progress of these bugs.

Cheers,
 Mario
