### ISSUE TITLE
Support for NetCore 3.0

### ISSUE THREAD

**Issue by SebastianAtWork** [mariotoffia/FluentDocker#116]
Hi,
It would be great if this library supports NetCore 3.0.
Currently, i get an Exception thrown: 'System.MissingMethodException' in System.Private.CoreLib.dll
Method not found: 'Microsoft.Extensions.Logging.ILoggerFactory Microsoft.Extensions.Logging.DebugLoggerFactoryExtensions.AddDebug(Microsoft.Extensions.Logging.ILoggerFactory)'.

**Comment by mariotoffia** [comment]
Yes indeed! I'll add it to the next release.

Cheers,
 Mario

**Comment by mariotoffia** [comment]
I've tested the new compile to netcoreapp3.0 since I've added netstandard2.1 as a additional target it should work for you when I do the next release. If you want to test it now, just checkout the master branch and test it out...

Cheers,
 Mario

**Comment by SebastianAtWork** [comment]
Cool, will test it out and report back :) Thanks for the quick answer

**Comment by SebastianAtWork** [comment]
I tried it out but still get the same error:
![image](https://user-images.githubusercontent.com/19798013/66705768-5790e100-ed2b-11e9-80a7-5b803fab9eed.png)

**Comment by mariotoffia** [comment]
Hi @SebastianAtWork Have you tried to clone the master branch and tried to run the test project. Make sure that the ```RunContainers()``` method invocation is uncommented in ```Tests.Program.Main```. Use the _master_ branch when cloing. Build and run it. You should have netcoreapp3.0 and the the standard dependencies should be 2.1.0 and 4.3.0.

Can you test this and tell me how it went for you?

Cheers,
 Mario

![image](https://user-images.githubusercontent.com/1716527/66717678-0a207c80-eddc-11e9-8d32-a393c747245b.png)

**Comment by SebastianAtWork** [comment]
Very cool, using the master branch, the test works. it throws some socket exceptions until the postgress container is ready but then it works. And using the resulting nuget, even my project works :) 
Very cool project, keep up the good work 👍

**Comment by mariotoffia** [comment]
@SebastianAtWork The SocketException thing is that it uses WaitForPort of which it will try to connect until succeeds - hence the `SocketExceptoin` :)

Glad you like it! :)
 Mario
