### ISSUE TITLE
Ability to set --dns on a container via fluent api

### ISSUE THREAD

**Issue by seertenedos** [mariotoffia/FluentDocker#122]
I can see that is the lower level classes the setting of the dns server is supported but the Fluent api does not let you specify the DNS server for a conatiner.

**Comment by mariotoffia** [comment]
I've created a pre-release with this functionality. Can you test and see so it works for your needs? It is located at https://www.nuget.org/packages/Ductus.FluentDocker/2.7.19-beta0030 or _tick_ pre-release when importing nuget package. 

Please reply here of the outcome.

Cheers,
 Mario

**Comment by seertenedos** [comment]
Thanks i can confirm that i can see the entries in the ResolvConf so it seems to be working correctly
