### ISSUE TITLE
Deploy to nuget.org pre-releases automatically

### ISSUE THREAD

**Issue by MindaugasLaganeckas** [mariotoffia/FluentDocker#123]
Please, have a look at this project: https://github.com/nmklotas/GitLabApiClient/

Relevant files:
1. GitVersion.yml
2. GitLabApiClient.csproj
3. appveyor.yml

I could create a pull request if you agree with a feature (or you can do it yourself if you prefer).

**Comment by mariotoffia** [comment]
Many thanks for your guideline - I did it myself since I was curious how to do this. The first pre-release is https://www.nuget.org/packages/Ductus.FluentDocker/2.7.4-beta0001.

If you got time, please have a check on the setup and advice me if I did something wrong!

Cheers,
 Mario :)

**Comment by MindaugasLaganeckas** [comment]
It works very nicely! Thanks a bunch! I do not need to build and deploy locally any longer! :)

Best,
Mindaugas
