### ISSUE TITLE
Health Check and WaitForHealthCheck

### ISSUE THREAD

**Issue by seertenedos** [mariotoffia/FluentDocker#130]
In other parts of the code you have
 WithHealthCheck(string cmd, string interval = null, string timeout = null, string startPeriod = null, int retries = 3)
but when using the 
new Builder().UseContainer()
you only get 
.HealthCheck(string)
and
.WaitForHealthy(TimeSpan)

The issue i hit is since i can't control when the health check is run or the frequency then you must wait the default 30 seconds that is configured on the health check before it will report as being healthy. If you are starting multiple containers it means you need to wait atleast 30 seconds on each of them for a test that may be able to be done every 5 seconds for example and would have only needed to wait 5 seconds.

**Comment by mariotoffia** [comment]
Thanks for this, hmm... I'll do the fix this weekend and will be part of a pre-release.

**Comment by mariotoffia** [comment]
@seertenedos I've done a few updates (you may now override more parameters of the Dockerfile _HEALTHCHECK_ section if you want using the _FluentAPI_. I've also added more documentaiton (see below).

I've added clarification on `UseHealthCheck(...)` <- old Health will be deprecated since the new one supports overriding **all** parameters. In addition `WaitForHealthy` is also documented to clarify the prurpose of it.

```cs
   /// <summary>
    /// Sets or overrides the native HEALTHCHECK provided by the docker daemon.
    /// </summary>
    /// <param name="cmd">A commnad to preform the health check.</param>
    /// <param name="interval">How ofthen to perform the <paramref name="cmd"/>, default is 30s.</param>
    /// <param name="timeout">How long time the <paramref name="cmd"/> has in order to not be marked as unhealthy container.</param>
    /// <param name="startPeriod">How long for the first execution of <paramref name="cmd"/>, default is 30s.</param>
    /// <param name="retries">The number of retries a <paramref name="cmd"/> has in order for the container do be marked as unhealthy, default is 3.</param>
    /// <returns>Itself for fluent access.</returns>
 public ContainerBuilder UseHealthCheck(...) {}
```

...and wait...

```cs
/// <summary>
    /// This install a wait for a docker daemon HEALTH check until certain timeout to set to Healthy.
    /// </summary>
    /// <param name="timeout">A optional timeout to stop waiting.</param>
    /// <returns>Itself for fluent access.</returns>
    /// <remarks>
    ///   When the container is in <see cref="ServiceRunningState.Running"/> mode it will poll
    ///   the container configuration and check the health of the container (as classified by the
    ///   docker daemon). When the container is reported as Healthy, this method silently exits.
    ///   If timeout a <see cref="FluentDockerException"/> is thrown. The status is deemed
    ///   by the containers Dockerfiles HEALTH section or if overrided / created by
    ///   <see cref="UseHealthCheck(string, string, string, string, int)"/>.
    /// </remarks>
    public ContainerBuilder WaitForHealthy(TimeSpan timeout = default) {}
```

I hope it solves your problem? It will be part of the next pre-release (tonight).

Cheers,
 Mario

**Comment by seertenedos** [comment]
Thanks that looks perfect.
