### ISSUE TITLE
Support for NVIDIA runtime

### ISSUE THREAD

**Issue by seertenedos** [mariotoffia/FluentDocker#132]
I was trying to set up a container to use the nvidia runtime to be able to use GPU accelleration and realised it is missing from the fluent API. Could it be added as well?

--runtime=nvidia   is what i would normally put on the command line when creating the container instance.

**Comment by mariotoffia** [comment]
I've created a PR #133. I don't have any possibility to test this out. Could you please do a unit-test to make sure that it will succeed?

Cheers,
 Mario

**Comment by mariotoffia** [comment]
I'm assuming this works OK so I'm closing it. I have no way of testing this function.

**Comment by seertenedos** [comment]
Yea sorry I just found I have no way of testing it yet either as my Dev PC
does not have an NVIDIA. Only my prod machine does so I need to get more
things working first to test it out
