### ISSUE TITLE
Project quality monitored by SonarCloud

### ISSUE THREAD

**Issue by MindaugasLaganeckas** [mariotoffia/FluentDocker#135]
Hey @Mario-Hofstaetter,
Would you be interested in integrating your project with https://sonarcloud.io?
I think it is the next natural step for having a good overview of your project (quality, bugs, code smells, coverage etc).
I would be willing to help if any help is needed.

Best regards,
Mindaugas

**Comment by mariotoffia** [comment]
@MindaugasLaganeckas Thanks!, I've setup the initial integration. I haven't configured anything - will do that in a later iteration.

Cheers,
 Mario

**Comment by mariotoffia** [comment]
@MindaugasLaganeckas Hi, how do I exclude stuff since the only complains is from test java script files from other project...

1) Code duplication in files:
    Ductus.FluentDocker.Tests/MultiContainerTestFiles/index.js | 100% | 28
    Ductus.FluentDocker.Tests/Compose/node/index.js | 100% | 28
2) Bug in file:
    "Expected an assignment or function call and instead saw an expression.See Rule"
     Ductus.FluentDocker.Tests/MultiContainerTestFiles/app.js

[My sonarcloud project](https://sonarcloud.io/dashboard?id=mariotoffia_FluentDocker)

Cheers,
 Mario

**Comment by MindaugasLaganeckas** [comment]
@mariotoffia I will either make a pull request or get back to you with instructions. I am looking into it :)

**Comment by MindaugasLaganeckas** [comment]
@mariotoffia I am still looking into the issue. I still miss code coverage: https://sonarcloud.io/dashboard?id=MindaugasLaganeckas_FluentDocker. I will continue working on it, so you do not need to worry. Will contact you, when I am done.

**Comment by mariotoffia** [comment]
@MindaugasLaganeckas  Thanks for helping me out! :)

Cheers,
 Mario

**Comment by mariotoffia** [comment]
It is now running the scan and is visible in sonarcloud at https://sonarcloud.io/dashboard?id=mariotoffia_FluentDocker

Cheers,
 Mario
