### ISSUE TITLE
Consider using release drafter?

### ISSUE THREAD

**Issue by jetersen** [mariotoffia/FluentDocker#139]
release drafter is an neat GitHub action/app that helps you draft the releases and is highly customizatiable it can help give recognition to those who contributed

See 
https://github.com/nmklotas/GitLabApiClient/releases
https://github.com/jenkinsci/jenkins/releases
https://github.com/jenkinsci/configuration-as-code-plugin/releases
https://github.com/casz/express-ipfilter/releases

**Comment by mariotoffia** [comment]
Thanks, I'll have a check in this during Christmas and if any good I'll integrate that! :)
