### ISSUE TITLE
GetContainers performance

### ISSUE THREAD

**Issue by truepele** [mariotoffia/FluentDocker#145]
DockerHostService.GetContainers is slow comparing to docker cli.

"docker inspect $(docker ps --all --quiet)" vs DockerHostService.GetContainers:
containers cnt | docker cli, ms | GetContainers, ms
1                      | 95                  | 400
2                      | 105                | 545
8                      | 125                | 700
16                    | 160                | 1020
32                     | 210               | 1650

Tested on:
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro14,3
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	2.8 GHz

**Comment by mariotoffia** [comment]
merged into master
