### ISSUE TITLE
new Host().Discover() fails on Mac with Docker Desktop Community 2.2.0.0 because docker-machine is no longer included

### ISSUE THREAD

**Issue by damianh** [mariotoffia/FluentDocker#150]
We suddenly started getting this error messages on developer mac machines:

```
Host terminated unexpectedly: System.ComponentModel.Win32Exception (2): No such file or directory
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ductus.FluentDocker.Executors.ProcessExecutor`2.Execute()
   at Ductus.FluentDocker.Services.Hosts.Discover(Boolean preferNative)
```

The culprit being:

1. [This code](https://github.com/mariotoffia/FluentDocker/blob/master/Ductus.FluentDocker/Commands/Machine.cs#L34-L35) trying to run `docker-machine`
2. As of 2.2.0.0 `docker-machine` is no longer distributed with Docker for Mac https://docs.docker.com/docker-for-mac/release-notes/

We had to debug through the library to see what was happening and it took a while 😬 .

The solution was to install `docker-machine` seperately ( https://github.com/docker/machine/releases ).

However I think the library could give a better error with a try-catch-throw around the `Process.Start()` [here](https://github.com/mariotoffia/FluentDocker/blob/master/Ductus.FluentDocker/Executors/ProcessExecutor.cs#L75)

**Comment by mariotoffia** [comment]
Agreed, I Will fix both nicer errormsg and by default supress if machine is mässing (configurable).

Cheers

**Comment by mariotoffia** [comment]
@damianh  Which version of _FluentDocker_ are you running. I've also missing docker machine but it works ok.

**Comment by mariotoffia** [comment]
@damianh I've also committed (as pre-release nuget binary) some more error handling and guidance when `docker-machine` is missing. If you have a old version, pleas update and let me know if it works ok?

Cheers,
 Mario

**Comment by damianh** [comment]
Will give it a spin!

**Comment by mariotoffia** [comment]
@damianh Hi, how did it work out?

**Comment by damianh** [comment]
Tested on co-workers laptop, got the nicer exception message. All good. 👍
