### ISSUE TITLE
Compose Dispose always throws exception

### ISSUE THREAD

**Issue by ptsneves** [mariotoffia/FluentDocker#151]
https://github.com/mariotoffia/FluentDocker/blob/9c4bbcafe1f5fcc70bc11d4c64b4aec138dbf5bc/Ductus.FluentDocker/Services/Impl/DockerComposeCompositeService.cs#L50

This line is always called even though the docker-compose down is successful. I do not know how can I debug this, so i just catch the exception. Let me know if there is more information i can provide

**Comment by mariotoffia** [comment]
Can you provide with a simple test si I can recreate it?

**Comment by mariotoffia** [comment]
@ptsneves Hi, since I haven't heard from you and not able to reproduce on my side. I will close this issue tomorrow. If you still have problem, can you please assemble a little test so I may debug and solve your problem.

**Comment by ptsneves** [comment]
Hello @mariotoffia today when i get home i will try to provide it. You can close it until i do so it does not mess the bug tracker. Thanks for the support
