### ISSUE TITLE
Please remove the VS output window "Program Output" spam

### ISSUE THREAD

**Issue by Thx1137** [mariotoffia/FluentDocker#152]
Awesome work on the library, there is just one annoyance though. I get massive amounts of the following while using the library. I really only want to see my own program output messages in there.

cmd: C:\Program Files\Docker\Docker\resources\bin\docker.exe - arg:  -H npipe:////./pipe/docker_engine ps  --all --quiet --no-trunc

**Comment by mariotoffia** [comment]
There is a logging Setup - please check issue #49 for details.

**Comment by Thx1137** [comment]
@mariotoffia Thanks, sorry for the unnecessary report!
