### ISSUE TITLE
NetworkExtensions.ToHostPort returns wrong host endpoint

### ISSUE THREAD

**Issue by gitfool** [mariotoffia/FluentDocker#158]
I've hit an issue with [NetworkExtensions.ToHostPort](https://github.com/mariotoffia/FluentDocker/blob/master/Ductus.FluentDocker/Services/Extensions/NetworkExtensions.cs#L133-L136):
```c#
if (CommandExtensions.IsEmulatedNative())
  return CommandExtensions.IsDockerDnsAvailable()
    ? new IPEndPoint(CommandExtensions.EmulatedNativeAdress(), endpoints[0].Port)
    : new IPEndPoint(IPAddress.Loopback, endpoints[0].Port);
```
First of all, what is [CommandExtensions.EmulatedNativeAdress](https://github.com/mariotoffia/FluentDocker/blob/master/Ductus.FluentDocker/Extensions/CommandExtensions.cs#L153-L156) supposed to represent?
```c#
public static bool IsEmulatedNative()
{
  return !FdOs.IsLinux() && !IsToolbox();
}
```
(This is true for me while running [Docker Desktop for Windows](https://docs.docker.com/docker-for-windows/edge-release-notes/).)

Next, what has that got to do with [CommandExtensions.IsDockerDnsAvailable](https://github.com/mariotoffia/FluentDocker/blob/master/Ductus.FluentDocker/Extensions/CommandExtensions.cs#L159-L171)?
```c#
public static bool IsDockerDnsAvailable()
{
  try
  {
    Dns.GetHostEntryAsync("docker").Wait();
    return true;
  }
  catch (AggregateException ex)
    when (ex.InnerExceptions.Count == 1 && ex.InnerExceptions[0] is SocketException)
  {
    return false;
  }
}
```
... because this erroneously looks up the ip address for the "docker" dns name, which resolves to another machine on our network, not my machine! (We have a separate Linux machine setup for users without Docker installed locally.)

Why is this "docker" dns name used at all? 😕

**Comment by gitfool** [comment]
I don't suppose this is trying to handle the "Docker in Docker" scenario? i.e. when get the host when FluentDocker is itself running in Docker?

* dns name `docker.for.win.localhost` was added in 17.06.0 ([Windows](https://docs.docker.com/docker-for-windows/release-notes/#docker-community-edition-17060-ce-win18-2017-06-28))
* dns name `docker.for.mac.localhost` was added in 17.06.0 ([Mac](https://docs.docker.com/docker-for-mac/release-notes/#docker-community-edition-17060-ce-mac18-2017-06-28))

Both names were later deprecated in favor of a platform independent dns name:

* dns name `host.docker.internal` was added in 18.03.0 ([Windows](https://docs.docker.com/docker-for-windows/release-notes/#docker-community-edition-18030-ce-win59-2018-03-26))
* dns name `host.docker.internal` was added in 18.03.0 ([Mac](https://docs.docker.com/docker-for-mac/release-notes/#docker-community-edition-18030-ce-mac59-2018-03-26))

> DNS name host.docker.internal shoud be used for host resolution from containers. Older aliases (still valid) are deprecated in favor of this one. (See https://tools.ietf.org/html/draft-west-let-localhost-be-localhost-06).

So if this is the intention of the code above, it should be updated to looking up the _fully qualified_ dns name `host.docker.internal`.

**Comment by mariotoffia** [comment]
Yes, this is from the early days of windows docker toolbox. Many thanks for cleaning this up!

Cheers,
 Mario :)
