### ISSUE TITLE
Unable to expose UDP connection

### ISSUE THREAD

**Issue by DR9885** [mariotoffia/FluentDocker#163]
Want to call
```$ docker run -d -p 8500:8500 -p 8600:8600/udp```

REF: https://learn.hashicorp.com/tutorials/consul/docker-container-agents#configure-and-run-a-consul-server

**Comment by mariotoffia** [comment]
Hi @DR9885 and thanks for the feature request. I did skip UDP (a long time ago) as a design descision and now need to revisit that.

Cheers,
 Mario :)

**Comment by mariotoffia** [comment]
@DR9885  Sorry for the late commit, I've added support to pass `protocol` in `ExposePort`. It defaults to _tcp_ but may be used to pass _udp_ instead. It will be available in pre-release, on nuget, in one hour or so.

Cheers,
 Mario :)
