### ISSUE TITLE
Add support for ENV in FileBuilder

### ISSUE THREAD

**Issue by macsux** [mariotoffia/FluentDocker#177]
When building up image definition via `FileBuilder`, should allow defining Dockerfile `ENV` directive

**Comment by mariotoffia** [comment]
I've compiled a pre-release - please have a go https://www.nuget.org/packages/Ductus.FluentDocker/2.8.8-beta.14

**Comment by mariotoffia** [comment]
@macsux Please report back if it works or if you have any issues.

**Comment by macsux** [comment]
ENV is awkward to work with, and can't chain multiple values into one command easily. I propose something like this:

```csharp
        class EnvCommand : ICommand
        {
            public Dictionary<string, string> Values { get; }

            public EnvCommand(Dictionary<string, string> values)
            {
                Values = values ?? new();
            }

            public override string ToString()
            {
                return $"ENV {string.Join(" \\\n    ", Values.Select(x => $"{x.Key}={x.Value}"))}";
            }
        }
```

```csharp
        public FileBuilder Environment(this FileBuilder builder, Dictionary<string, string> values)
        {
            _config.Commands.Add(new EnvCommand(values));
            return builder;
        }
```

**Comment by macsux** [comment]
Image builder should have an overload for its `From` with `asLabel` into FileBuilder.

**Comment by mariotoffia** [comment]
I don't quite follow you - what is the problem with this?

```cs
new EnvCommand(
          "MY_ENV=a env",
          "NEXT_ENV=next var",
          "PASSWORD=DbPass-for-admin"
);
```

**Comment by macsux** [comment]
Template string doesn't really tell me the correct syntax I need to
provide. I'm mainly guessing at that point. Are the values separated by =,
is it an alternating array of key/value pairs? Dictionary makes this very
intuitive.

**Comment by mariotoffia** [comment]
Yes, but it is how the other env API already work 

e.g. `public CompositeBuilder WithEnvironment(params string[] nameValue)`, `public ContainerBuilder WithEnvironment(params string[] nameValue)`, ... 

- added to v2 list of changes - for v1 the name `nameValue´ has to suffice.
