### ISSUE TITLE
Add support for multistage labels in FileBuilder

### ISSUE THREAD

**Issue by macsux** [mariotoffia/FluentDocker#178]
Allow assigning labels in `FileBuilder` for intermediate container images such as 
```Dockerfile
FROM someimage AS myImage
```

and allow referring to in `COPY` directive to generate Dockerfile equivalent of
```Dockerfile
COPY --from=myImage ["/app", "/app"] 
```

**Comment by mariotoffia** [comment]
I've compiled a pre-release - please have a go https://www.nuget.org/packages/Ductus.FluentDocker/2.8.8-beta.14

**Comment by mariotoffia** [comment]
@macsux Please report back if it works or if you have any issues.

**Comment by macsux** [comment]
Image builder should have an overload for its From with asLabel into FileBuilder.

**Comment by mariotoffia** [comment]
Hmmm I'm unsure what you want here. What would this duplicate `asLabel`  provide with that `From` do not provide?

**Comment by macsux** [comment]
Because you can start `From` on the ImageBuilder, the overload that includes "asLabel" parameter should be available on the ImageBuilder as well.

**Comment by mariotoffia** [comment]
Got'ya
