### ISSUE TITLE
Allow creating FileBuilder without specifying initial command

### ISSUE THREAD

**Issue by macsux** [mariotoffia/FluentDocker#179]
Currently `FileBuilder` is started from ImageBuilder via `From` method, but this adds first "command" to the sub-builder. This gets awkward when adding conditional buildup of container image, where first command to be added is not easily identified. This requires tricks like the use of a local function:
```csharp
FileBuilder From(string image) => fileBuilder == null
            ? builder.From(image)
            : fileBuilder.From(image);
```

It would be better if FileBuilder can be started without adding the initial command.

**Comment by mariotoffia** [comment]
I've compiled a pre-release - please have a go https://www.nuget.org/packages/Ductus.FluentDocker/2.8.8-beta.14

**Comment by mariotoffia** [comment]
@macsux Please report back if it works or if you have any issues.

**Comment by macsux** [comment]
I think relying on `From` with empty string to implement this is awkward. I suggest adding a new method like `DockerfileBuilder` to `ImageBuilder`.

**Comment by mariotoffia** [comment]
I would say the this is consistent how the API do work e.g. `public ImageBuilder DefineImage(string image = null)`. I do not say it is optimal and many things will change when 2.0.0 is released but for now I try to stick to be as consistent as possible.
