### ISSUE TITLE
FromCommand is not adding AS keyword when label is specified

### ISSUE THREAD

**Issue by macsux** [mariotoffia/FluentDocker#181]
Expected
`.From("mcr.microsoft.com/dotnet/sdk:5.0", "net5.0")` -> `FROM mcr.microsoft.com/dotnet/sdk:5.0 AS net5.0`

Actual
`.From("mcr.microsoft.com/dotnet/sdk:5.0", "net5.0")` -> `FROM mcr.microsoft.com/dotnet/sdk:5.0 net5.0`

**Comment by mariotoffia** [comment]
True! and fixed in PR #184
