### ISSUE TITLE
Add support for URL based source on FileBuilder ADD command

### ISSUE THREAD

**Issue by macsux** [mariotoffia/FluentDocker#182]
Add command doesn't work when specifying URL as a source 
```csharp
filebuilder.Add(@"https://aka.ms/vs/16/release/vs_buildtools.exe", "C:/TEMP/vs_buildtools.exe")
```

There's also the additional issue of it mutating builder in a way where repeated invocations incosistent. From pattern perspective builder inputs are not supposed to be altered during construction.

https://github.com/mariotoffia/FluentDocker/blob/781c884bcbeed34527b70cb6ee62b29677ef4a1e/Ductus.FluentDocker/Builders/FileBuilder.cs#L280

**Comment by mariotoffia** [comment]
good point, happy to accept a PR!
