### ISSUE TITLE
Builder Does Not Support Specifying tcp/Arbitrary IHostService, *Builder classes Cannot Be Extended

### ISSUE THREAD

**Issue by lordmilko** [mariotoffia/FluentDocker#185]
In my program, users will be able to customize the URI of the docker service they wish to connect to via a config file, thereby allowing users to connect to `tcp://<arbitraryAddress>:2375` without need to specify this as their `DOCKER_HOST` environment variable.

At the lowest level, I can easily create an `DockerHostService` that encapsulates this custom Docker URI, however I've found when it comes to using the fluent API, there doesn't appear to be a way to specify either the arbitrary `IHostService` I've created, or simply specify a `tcp://` based one.

The `HostBuilder` returned from `new Builder().UseHost()` only appears to support building three types of `IHostService` objects
1. Native, by specifying `.UseNative().Build()`
2. An SSH connection, by specifying `.UseSsh(...).Build()`
3. A Docker Machine connection, by specifying `.UseMachine().Build()`

I would propose that an additional method should be added, perhaps `UseTcp(...)`, `UseUri(...)` or `UseHost(IHostService service)` that enables an arbitrary host be used in fluent contexts. Users could theoretically implement such methods themselves if they wanted to by extending `HostBuilder`, however unfortunately it appears that most of the `*Builder` classes are actually `sealed` with `internal` constructors, making this a bit more complicated.

Fortunately, since `BaseBuilder<T>` simply has a `protected` constructor  I was able to *effectively* workaround this in my application by creating an `IBuilder` extension method that returns a custom `BaseBuilder<IHostService>`, however since I need to re-implement `UseContainer` this required the use of reflection since the `ContainerBuilder` constructor is not public.

```c#
static class BuilderExtensions
{
    public static HostBuilderEx UseHost(this IBuilder parent, IHostService hostService) =>
        new HostBuilderEx(parent, hostService);
}

class HostBuilderEx : BaseBuilder<IHostService>
{
    private IHostService hostService;

    public HostBuilderEx(IBuilder parent, IHostService hostService) : base(parent)
    {
        this.hostService = hostService;
    }

    public override IHostService Build() =>
        hostService;

    protected override IBuilder InternalCreate() =>
        new HostBuilderEx(this, hostService);

    public ContainerBuilder UseContainer()
    {
        var builder = (ContainerBuilder) Activator.CreateInstance(
            typeof(ContainerBuilder),
            BindingFlags.Instance | BindingFlags.NonPublic,
            null,
            new[] {this},
            null
        );
        Childs.Add(builder);
        return builder;
    }
}
```

```c#
var hostService = new DockerHostService("native", true, false, Settings.DockerUri, isWindowsHost: true);

var container = new Builder()
    .UseHost(hostService)
    .UseContainer()
    ...
```

As such, I would present it could potentially be useful to implement additional methods on `HostBuilder` for utilizing additional `IHostService` types in fluent contexts, and/or unsealing the various `*Builder` types that are available so that they can be more easily extended.

**Comment by mariotoffia** [comment]
@lordmilko  Thanks for this really good explained issue. I'll add support for custom `IHostService`.  I think it's better that we do as you just did - file a issue and I'll or the one files a issue - files a PR so we can make this library great for everyone :).

**Comment by mariotoffia** [comment]
@lordmilko  I've added both ability to add a `IHostService´ and a shorthand `FromUri` so your above example would look like.

```cs
using(var container = Fd.UseHost().FromUri("uri", isWindowsHost: true).
                                  .UseContainer().Build()) 
{
}
```

There are some other parameters for `FromUri`. But if that is not sufficient, you may use `UseHost(IHostService)`.

Cheers,
 Mario :)

**Comment by lordmilko** [comment]
Thanks @mariotoffia,

I also stumbled upon the fact this also appears to be the same issue as described in #105, so potentially this may allow both issues to be closed

**Comment by mariotoffia** [comment]
@lordmilko I would say it partially solves #105 since it was derived another issue from that one - issue #160 so it will support docker-compose along with docker contexts.

I would like to state that I really like your issue, good explanation so it is crystal clear what you want! - Thanks! :)

**Comment by lordmilko** [comment]
Hi @mariotoffia,

Today I noticed you had pushed FluentDocker 2.10.2 with this change last week! I was able to try it out and can confirm everything is working as expected; one curious thing I did note however, I personally found the syntax surrounding the new `UseHost` method a bit confusing.

In the README it states that

> UseHost that takes a instantiated IHostService implementation.

While it doesn't provide an example, it seems fairly logical based on this that you can probably do something like:

```c#
var hostService = new DockerHostService(...);

var container = Fd
    .UseHost(hostService)
    ...
```

But this is incorrect! In fact, the syntax is actually

```c#
var hostService = new DockerHostService(...);

var container = Fd
    .UseHost()
    .UseHost(hostService)
    ...
```

In order to use your custom `IHostService` you have to call *two* methods called `UseHost`, where each method has a slightly different meaning (the first refers to using a host `Builder`, while the second method refers to using a host `Service`) which strikes me as a bit of a strange design pattern

I think it would probably make more sense as

```c#
var container = Fd
    .UseHost()
    .WithHostService(hostService)
    ...
```

or something, which would be consistent with how you can do

```c#
    .UseImage(...)
    .WithName(...)
    .WithHostName(...)
```

of course, for me my program is now working without the need for my own custom workaround. Potentially this may be something worth considering however.

Thanks for your help!

Regards,
lordmilko

**Comment by mariotoffia** [comment]
@lordmilko  Great suggestion!! - Hmm... yes, kid'a cookie ontop of cookie as we say in sweden :). What do you think about 

```cs
var container = Fd
    .UseHost()
    .WithCustomHost(hostService)
    // or
var container = Fd
    .UseHost()
    .FromService(hostService)
   // or
var container = Fd
    .UseHost()
    .AsService(hostService)
```
?

Cheers,
 Mario :)

**Comment by lordmilko** [comment]
Hi @mariotoffia,

I spent a bit of time thinking about this! And I would say `WithService` is probably best

* `WithCustomHost` is ambiguous - what is a "host" - are we talking about a host *builder* or host *service*. It's also a bit verbose (having only two words in a fluent operation is probably better than three)
* `FromService` seems OK at first, however when you compare it to `FromUri` it doesn't make sense; `FromUri` creates a host *service* **from** a URI **for** your `HostBuilder`. `FromService` doesn't create anything **from** a service, rather it modifies the `HostBuilder` to execute **with** your specified `IHostService`
* "as" applies performing a conversion in C#, but `AsService` doesn't convert anything at all

As such, by process of elimination I think `WithService` works best

**Comment by mariotoffia** [comment]
Neat! :) I'll add it to my todo for the week - I will make this change in hope that not too many have used this particular method since I'm going to do a rename, hence incompatibility is introduced even if the semver do not denote such - hope this is ok for you.

Thanks for your help!

Cheers,
 Mario :)

**Comment by mariotoffia** [comment]
done, will come in a release this week
