### ISSUE TITLE
Add xUnit support

### ISSUE THREAD

**Issue by hatzhang** [mariotoffia/FluentDocker#189]
So this can be used like those testcontainers.

**Comment by mariotoffia** [comment]
Thanks @hatzhang  for this great idea. I'll have a check and see when I get some time to create a new nuget package for this.

**Comment by mariotoffia** [comment]
Hi @hatzhang, @jgozner has fixed this and it's about to be built in ```master``` - if everything builds _OK_ it will be present in NuGet in about 30 minutes or so.

Cheers,
 Mario :)
