### ISSUE TITLE
[Feature Request] Async command to ensure Image is pulled

### ISSUE THREAD

**Issue by pdevito3** [mariotoffia/FluentDocker#198]
It would be really helpful if we had a way to ensure that an image is pulled on the machine. For example,

```csharp
 var hosts = new Hosts().Discover();
var docker = hosts.FirstOrDefault(x => x.IsNative) ?? hosts.FirstOrDefault(x => x.Name == "default");
await docker.CreateImageAsync($"{DB_IMAGE}:{DB_IMAGE_TAG}");
```

Currently, I need to do it through `Docker.Net` like so:

```csharp
        private static bool IsRunningOnWindows()
        {
            return Environment.OSVersion.Platform == PlatformID.Win32NT;
        }

        public static DockerClient GetDockerClient()
        {
            var dockerUri = IsRunningOnWindows()
                ? "npipe://./pipe/docker_engine"
                : "unix:///var/run/docker.sock";
            return new DockerClientConfiguration(new Uri(dockerUri))
                .CreateClient();
        }


        public static async Task EnsureImagePulled(string image)
        {
            var dockerClient = GetDockerClient();

            // Ensure that the latest Docker image is pulled
            await dockerClient.Images.CreateImageAsync(new ImagesCreateParameters
            {
                FromImage = image
            }, null, new Progress<JSONMessage>());
        }
            
```

**Comment by pdevito3** [comment]
Nevermind... looks like i can do this `docker.Create($"{DB_IMAGE}:{DB_IMAGE_TAG}");` with fluent docker. Seems like i need to go to bed!

**Comment by mariotoffia** [comment]
💡  **@pdevito3 - This expands on the answer you wrote above if someone else will hit the same problem!**

Exactly! 😃, as you stated it is possible to control it using force pull either in the builder (via `UseImage(string image, bool force = false`) or directly on the `DockerHostService.Create`. 

However, the latter may be a bit cumbersome to invoke (better to use the _FluentAPI_ builder instead 😃)

🐅 **Manually create a `DockerContainerService` instance (the hard way ;)**
```cs
IContainerService Create(string image, bool forcePull = false, ContainerCreateParams prms = null,
  bool stopOnDispose = true, bool deleteOnDispose = true, bool deleteVolumeOnDispose = false,
  bool deleteNamedVolumeOnDispose = false, string command = null,
  string[] args = null, 
  Func<Dictionary<string, HostIpEndpoint[]>, string, Uri, IPEndPoint> customEndpointResolver = null);
```
(notice the _forcePull_ parameter, when set to true it will do the following

```cs
if (forcePull)
{
  var force = Host.Pull(image, Certificates);
  if (!force.Success)
    throw new FluentDockerException($"Could not pull image ${image}. Result: {force}");
}
```

Another "library" _option_ do exist (used in unit tests) called 
```cs
EnsureImage(string image, TimeSpan ts)
``` 
(in the `Ductus.FluentDocker.Tests.Extensions` namespace). This function will try to pull an image for a set time period.

Cheers,
 Mario
