### ISSUE TITLE
Consider dropping .NET Standard 1.6

### ISSUE THREAD

**Issue by 0xced** [mariotoffia/FluentDocker#208]
I have started simplifying the projects and I noticed that almost all of conditional compilation (`#if COREFX`) is actually because of the .NET Standard 1.6 target framework.

So, would you consider dropping support for .NET Standard 1.6 in the next release? That would simplify a lot of things.

**Comment by mariotoffia** [comment]
Hi @0xced, yes, the plan is to drop it the next major (3.0.0) release.

**Comment by 0xced** [comment]
Good to know! Should I submit a pull request on the `master` branch or are you planing to create a new `v3` branch?

**Comment by 0xced** [comment]
Anyway, I have opened #209 which simplifies the projects without modifying the supported target frameworks. Il will be easy to drop .NET Standard 1.6 as I explained in the comments of this pull request.

**Comment by mariotoffia** [comment]
done!
