### ISSUE TITLE
Is there a way to set several parameters at once?

### ISSUE THREAD

**Issue by forfcw** [mariotoffia/FluentDocker#214]
sry, Is there a way to set several parameters at once such as " -t -d --privileged --device /dev/snd --restart=always "and etc,  of course I have realized the existing function  such as RestartPolicy, but sometimes it make things complicated. 
Looking forward to your recovery, tks！

**Comment by mariotoffia** [comment]
Hi, you may set all those parameters when using layer 1 (commands). Both _restart_ and _device_ is not present on the current _FluentAPI_  (`ContainerBuilder`).

If you need to use _--device_ and _--restart_, at the moment, please use the `ContainerCreateParams` and use that instance on e.g. `Create` (an _extension_ function that resides in the namespace `Ductus.FluentDocker.Commands`).

For example:

```cs
      using (var container = _host.Create("postgres:9.6-alpine", false,
        new ContainerCreateParams
        {
          Environment = new[] { "POSTGRES_PASSWORD=mysecretpassword" }
        }))
      {
        Assert.AreEqual(ServiceRunningState.Stopped, container.State);
      }
```
In the `ContainerCreateParams` you will find all the parameters that you mention such as `ContainerCreateParams..RestartPolicy`,  `ContainerCreateParams.Privileged` and `ContainerCreateParams.Device`.

If you *really* need to have them on the _FluentAPI_ builder (i.e. it is frequently used). Please let me know and I'll add them.

Cheers,
 Mario :)

**Comment by forfcw** [comment]
Got it, tks !!!
