### ISSUE TITLE
Performance of start/stop/remove container

### ISSUE THREAD

**Issue by forfcw** [mariotoffia/FluentDocker#215]
Have you got some performance problems with start/stop/remove containers?

```cs
var hosts = new Hosts().Discover();
var host = hosts.FirstOrDefault(x => x.IsNative) ?? hosts.FirstOrDefault(x => x.Name == "default");
var _container = host.Create("nginx:alpine",
    prms: new ContainerCreateParams
    {
        Name = "test",
        Network = "host",
        PortMappings = new string[] { "9111:80", "9112:443" },
        Volumes = new string[] { "/data/log:/var/log:rw" },
        RestartPolicy = RestartPolicy.Always
    });
_container.Start();
```

It usually takes 4s or more to start a container, sometimes finding and deleting a container even takes 6s.
```bash
[root@root:~]# dotnet test.dll 
start: 5.230721
stop: 1.2377657
remove:1.7702362
```
Looking forward to your recovery!

**Comment by mariotoffia** [comment]
Hi @forfcw. Unfortunately, I've done a simple test to test the start Issue.

In my case, I have a really weak hp dragonfly laptop with an "Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz, 1992 Mhz, 4 Core(s)" with probably not the fastest ram in the world ;)

Using the following sample (I will check it in this into Examples Solution later on)

```cs

        var container = new Builder().UseContainer()
                    .UseImage("postgres:9.6-alpine")
                    .ExposePort(5432)
                    .WithEnvironment("POSTGRES_PASSWORD=mysecretpassword")
                    .WaitForPort("5432/tcp", 30000)
                    .Build();

        Stopwatch stopwatch = new Stopwatch();
        stopwatch.Start();
        container.Start();
        Console.WriteLine("Start container: " + TimeSpan.FromMilliseconds(stopwatch.ElapsedMilliseconds).TotalSeconds);
```

Start container: 0.665 s 

Where it will wait until _postgres_ have started and exposes a _TCP_  port.

I will investigate further, but in the meantime can you please use the docker commands from the shell and clock how long a "nginx:alpine" takes to start and be deleted?

Cheers,
 Mario

**Comment by forfcw** [comment]
May be I wronged FULENTDOCKER, It takes the same time in shell!
