### ISSUE TITLE
GetImages filtering doesn't work

### ISSUE THREAD

**Issue by herbatnik** [mariotoffia/FluentDocker#219]
The line below should say `+=` instead of `=` because of that, when passing filter the parser fails to parse the response causing no images being returned at all

https://github.com/mariotoffia/FluentDocker/blob/326729108e539b8c499c3a674a3bf458a22a3b36/Ductus.FluentDocker/Commands/Client.cs#L108

**Comment by mariotoffia** [comment]
Hi @herbatnik and thanks for spotting this bug. I'll fix it during this weekend.

Cheers,
 Mario :)

**Comment by mariotoffia** [comment]
I've merged the fix - it will be available within 30 minutes or so

**Comment by herbatnik** [comment]
All works now. Thank you a lot for a quick fix ⚡
