### ISSUE TITLE
Support for docker compose v2.0.0 incl. using dock binary instead of docker-compose

### ISSUE THREAD

**Issue by Ross-Duckworth-Pharos** [mariotoffia/FluentDocker#221]
The recently released Docker Compose V2 (https://github.com/docker/compose/releases/tag/v2.0.0) introduces the following change: _container names use hyphens to produce a valid hostname_

This breaks the container name parsing in `ExtractName` in `Ductus.FluentDocker/Services/Impl/DockerComposeCompositeService.cs` which assumes underscores are being used (now hyphens are).

**Comment by mariotoffia** [comment]
Hi @Ross-Duckworth-Pharos and thanks for reporting this! 

I will add the possibility to AssumeComposeVersion / AutoDetect so it could use different strategies depending on version.

(another task is actually to allow for `docker compose` command as well.

Cheers,
 Mario :)

**Comment by psavva** [comment]
Docker-Compose v1 has been deprecated, and we should all switch to docker compose v2

Any ideas as to when this can be supported?

**Comment by psavva** [comment]
As a potential quick fix: 
`alias docker-compose="docker compose"`

**Comment by jchannon** [comment]
Just hit this same issue, is there a path forward

**Comment by mariotoffia** [comment]
There's a setting so you can specify the compose version `ComposeVersion.V2`. For example in the fluent API:

```cs
AssumeComposeVersion(ComposeVersion.V2)
```

Default is _Unknown_ and hence falls back to V1 behavoiur. This behaviour will be deprecated and migrated to default as V2 this year.

Cheers,
 Mario :)

**Comment by cvicenti-apr** [comment]
This does not seem to work when passing a docker-compose.yml file through DockerComposeCompositeService.
I'm using the following:
```
new DockerComposeCompositeService(
                DockerHost,
                new DockerComposeConfig
                {
                    ComposeFilePath = [filePath],
                    ForceRecreate = true,
                    RemoveOrphans = true,
                    StopOnDispose = true,
                    ComposeVersion = ComposeVersion.V2,
                    TimeoutSeconds = TimeSpan.FromSeconds(300)
                });
```
But it's still using V1 unfortunately

**Comment by renandegrandi** [comment]
I have the same problem here.
i am using the ComposeVersion.V2 in DockerComposeCompositeService but, when i run this in a container on gitlab runner i received the error:
`---- Ductus.FluentDocker.Common.FluentDockerException : Could not resolve binary docker-compose is it installed on the local system?`

My configuration: 
```
         return new DockerComposeCompositeService(
             DockerHost,
             new DockerComposeConfig
             {  
                 ComposeVersion = ComposeVersion.V2, 
                 ComposeFilePath = new List<string> { file },
                 ForceRecreate = true,
                 RemoveOrphans = true, 
                 StopOnDispose = true,
                 Wait = true
             });
```
