### ISSUE TITLE
DockerComposeCompositeService fails to start Container with Docker Desktop 4.3.0 and `Use Docker Compose V2` enabled

### ISSUE THREAD

**Issue by graves-k** [mariotoffia/FluentDocker#239]
This probably isn't an issue with the FluentDocker library, but I wanted to share this information with anyone else having the same issue. 
This was a reproducible issue with my team since updating to Docker Desktop v. 4.3.0. This update automatically enables the `Use Docker Compose V2` flag. 
Disabling `Use Docker Compose V2` seems to fix the issue.

 Error Message:
   Ductus.FluentDocker.Common.FluentDockerException : Could not dispose composite service from file(s) C:\path\docker-compose.yml
  Stack Trace:
     at Ductus.FluentDocker.Services.Impl.DockerComposeCompositeService.Dispose()

**Comment by mariotoffia** [comment]
Hi @graves-k , which version of _FluentDocker_ do you use?

**Comment by graves-k** [comment]
Thanks Mario,
We were using 2.10.42.
I confirmed that 2.10.44 has fixed this issue.

Thank you!
