### ISSUE TITLE
Support for Fluent memory limit in containers

### ISSUE THREAD

**Issue by bCamba** [mariotoffia/FluentDocker#243]
First of all, this is a great library! Thank you so much for it.

I needed a way to setup the memory limit of a container (as in docker run --memory or -m) but I did not find a way to do that in the high level fluent layer of the API, so I coded it myself here #244. I have created tests for it.

1. I noticed that in the **ContainerCreateParams** class there was an upper limit to the memory set of 4mb which I did not understand so I removed it.
2. I noticed that the **Convert** method in the **ConversionExtension** class had bugs so I fixed them and created tests for them even though this method is only used in one place.

I hope this helps.

**Comment by mariotoffia** [comment]
Thanks @bCamba for your great contribution! It is merged!

Cheers,
 Mario :)
