### ISSUE TITLE
Add BeforeContainerInitialized in FluentDockerTestBase ctor

### ISSUE THREAD

**Issue by miketof** [mariotoffia/FluentDocker#257]
derived ctor is called after the FluentDockerTestBase ctor so basically, the OnContainerInitialized can be used exchangeable with ctor of the inherited class. But if I want to do some operation before Build and Start - I can't. That's my proposition is to implement BeforeContainerInitialized() virtual method as the first line of FluentDockerTestBase ctor.

**Comment by mariotoffia** [comment]
Thanks @miketof  - I'll add it to my TODO list.

Thanks!
 Mario :)

**Comment by mariotoffia** [comment]
Hi @miketof  I've added several methods to participate in before build and before start - including before dispose (on error or test tear down).

Cheers,
 Mario :)
