### ISSUE TITLE
.Net Core support

### ISSUE THREAD

**Issue by smudge202** [mariotoffia/FluentDocker#31]
To be honest I just stumbled across this project; was hoping to use it to run some integration tests, but stumbled on the first hurdle. Is there any plans (is it even possible) to make this compatible with net core?

**Comment by mariotoffia** [comment]
I need to investigate if they have System.Process support that works good enough to use the docker binaries as I do in this project. I'll get back the next weekend to when I've done some investigations. If it seems ok (which it does at a first glance) I'll make sure that it runs under net core as well.

**Comment by smudge202** [comment]
I've been doing a bit of work on this here: https://github.com/smudge202/FluentDocker

Close to being able to compile everything, though confirming that I haven't broken anything as a result of the changes might prove to be a little more difficult.
