### ISSUE TITLE
ArgumentNullException executing Hosts.Discover

### ISSUE THREAD

**Issue by TioLuiso** [mariotoffia/FluentDocker#33]
Have just begun learning docker, and downloaded versión 17.3.1-ce. I am trying to use FluentDocker to setup and throw machines at integration tests. Looks like a good scenario for the library

However, trying to run Hosts.Discover() explodes with an ArgumentNullException.

Downloaded your code and run MachineServiceTests.DiscoverShouldReturnNativeWhenSuchIsPresent

Call Stack is

Newtonsoft.Json.Linq.Extensions.Value(IEnumerable`1 value)
Ductus.FluentDocker.Executors.Parsers.MachineInspectResponseParser.Process(ProcessExecutionResult response) in MachineInspectResponseParser.cs: line: 28
Ductus.FluentDocker.Executors.ProcessExecutor`2.Execute() in ProcessExecutor.cs: line: 68
Ductus.FluentDocker.Commands.Machine.Inspect(String machine) in Machine.cs: line: 23
Ductus.FluentDocker.Services.Hosts.<>c.<Discover>b__0_0(MachineLsResponse machine) in Hosts.cs: line: 23
System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
Ductus.FluentDocker.Services.Hosts.Discover() in Hosts.cs: line: 22
Ductus.FluentDockerTest.ServiceTests.MachineServiceTests.DiscoverShouldReturnNativeWhenSuchIsPresent() in MachineServiceTests.cs: line: 21

Checking it closely the problem lies at MachineInspectResponseParser.
To retrieve memory, it does 

MemorySizeMb = j["Driver"]["Memory"].Value<int>(),

but the objet it is trying to parse doesn't have a memory entry inside Driver. It has MemSize instead.

So it explodes

**Comment by mariotoffia** [comment]
Thanks for the report. I'll fix this during this week

**Comment by mariotoffia** [comment]
I've fixed it and published a net set of nugget packages (2.2.2) that handles both old style and new style of json payload.
