### ISSUE TITLE
Remove mounts on dispose

### ISSUE THREAD

**Issue by megafinz** [mariotoffia/FluentDocker#42]
Is there a way to declare container mounts to be disposable? Container dispose seems to remove only the container itself, but the mounts that were created with that container are left orphaned. It is useful in case I want to reuse the same mount with the same data on the next run, but there are times when I'd like to clear data that has been persisted in the mount between test runs.

**Comment by mariotoffia** [comment]
@megafinz Hi, I've added the support to use the fluent API to delete volumes when the container is disposed, just use the ```RemoveVolumesOnDispose()``` since by default the volumes are preserved.
If you use the container service, it is on the create method where this configuration is set.

I'll do a release on sunday - I've got some more networking to commit before release.

Cheers,
 Mario

**Comment by megafinz** [comment]
Thanks.

Will named volumes be removed also? I tried to make a quick PR to enable the `--volumes` flag in `rm` command, but it appears that it removes anonymous volumes only (https://docs.docker.com/engine/reference/commandline/rm/#remove-a-container-and-its-volumes). So removing named volumes is a bit more intricate operation, I think you have to `inspect` container first and then manually remove all volumes that are associated with it.

**Comment by mariotoffia** [comment]
I'm only deleting unnamed using the --volume as you described. 
Hmm... Is this a severe issue for you or could this wait? Since I will do the volume using the service pattern and thus this would be a easy task when that has been done but that's not due until one month or so...

**Comment by megafinz** [comment]
No, that's not a severe issue, I can use some workarounds.

Maybe add an overload to `Mount` (or even make another method like `AnonymousMount`) because it's not obvious what do I need to do in order to create anonymous mount (turns out that you need to pass empty string to `Mount` as first parameter).

**Comment by mariotoffia** [comment]
In the meantime I've added ```RemoveVolumesOnDispose(bool includeNamedVolues = false)``` in the of which will delete *all* named volumes include anonymous ones if it is set to true.

**Comment by mariotoffia** [comment]
I'm closing this issue since it will be fixed when I get to do the volumes properly. This will include complete control of which get's deleted and which are kept (selectively if you want) when disposing a container or set of containers.

**Comment by mariotoffia** [comment]
@megafinz I've added support for manageing volumes and thus lifetime of those and how they are mounted. It is both a fluent API and added mountVolume on container fluent api to use those volumes. You may then have control when and why the volumes are to be disposed or not. It is in 2.2.13
