### ISSUE TITLE
FluentDocker in GitLab pipeline

### ISSUE THREAD

**Issue by megafinz** [mariotoffia/FluentDocker#43]
I'm trying to run integration tests that use FluentDocker inside GitLab's CI pipeline, but I get this error:
```
System.TypeInitializationException : The type initializer for 'Ductus.FluentDocker.Extensions.CommandExtensions' threw an exception.
  ----> Ductus.FluentDocker.Common.FluentDockerException : Failed to find docker client binary - please add it to your path
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
   at Ductus.FluentDocker.Extensions.CommandExtensions.IsMachineBinaryPresent()
   at Ductus.FluentDocker.Services.Hosts.Discover()
```
Any idea how to fix this?

I presume this has something to do with how GitLab jobs are working: essentially GitLab creates docker image with our scripts in it, so test project is actually running inside docker, and the whole thing becomes docker-in-docker.

**Comment by mariotoffia** [comment]
As it states "Failed to find docker client binary" - it cannot find the docker executable of which fluentdocker is dependant on. You can install the docker client into the image of whch you build your solution. I do this using the azure build agent that I run in a docker container. So I too use docker in docker.

Cheers,
 Mario

**Comment by mariotoffia** [comment]
@megafinz Maybe this can help out?
https://docs.gitlab.com/ee/ci/docker/using_docker_build.html

**Comment by megafinz** [comment]
@mariotoffia sorry for the delay. You were right, for some reason I thought that my pipeline was based on the docker image, but it actually wasn't, hence no docker executable present. The issue is resolved now, thanks.
