### ISSUE TITLE
Is there a way to disable the command logging?

### ISSUE THREAD

**Issue by rlundy** [mariotoffia/FluentDocker#49]
Can I disable the Logger output?  Sometimes it's handy, but sometimes it just clutters my Debug window.

Is there some kind of configuration setting to turn it off?

**Comment by mariotoffia** [comment]
Yes, I don't know of the top of my head but it depends on if you're using the full framework or .net core.
It logs using the ```System.Diagnostics.Debugger.Log``` in full framework and the ```ILogger``` in .net core under the category ```Ductus.FluentDocker```.

Around this for .net core:
```
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Ductus.FluentDocker": "None"
      }
   }
}```


It is possible to do this in app.config for full framework  - checkout 
https://docs.microsoft.com/en-us/dotnet/framework/wcf/diagnostics/tracing/configuring-tracing

Cheers,
 Mario

**Comment by rlundy** [comment]
Very nice!  Do you how soon this change will be pushed to NuGet?

**Comment by mariotoffia** [comment]
I'll do it this weekend.

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by mariotoffia** [comment]
I've uploaded the release _2.3.1_. If there are any problems, please re-open this issue.

**Comment by rlundy** [comment]
Thank you for the package update!  I tried it out today and it works great.
