### ISSUE TITLE
Always Running

### ISSUE THREAD

**Issue by JolandavWyk** [mariotoffia/FluentDocker#50]
In powershell I would run:  docker run --name testing --restart always testapp:load1.0

How can I add the **--restart always** to the statement below?

            _docker.Host.Run("testapp:load1.0",
            new ContainerCreateParams()
            {
                Name = "testing113",
            }
            , _docker.Certificates);

Please assist.

Regards
Jolanda

**Comment by mariotoffia** [comment]
I've updated _fluentdocker_ and published a release including instructions how to do a ```RestartPolicy``` when _docker run_. It is in the release _2.3.1_. It is untested and if you get any problems, please reopen this issue!

**Comment by JolandavWyk** [comment]
Thanks a lot Mario.

I tested it RestartPolicy and it is working!!

Regards
Jolanda
