### ISSUE TITLE
Error: Failed to find docker client binary

### ISSUE THREAD

**Issue by JolandavWyk** [mariotoffia/FluentDocker#51]
When I run my code in a container I get an error: 

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Ductus.FluentDocker.Extensions.CommandExtensions' threw an exception. ---> Ductus.FluentDocker.Common.FluentDockerException: Failed to find docker client binary - please add it to your path

The error occurs on my first line of code:
var hosts = new Hosts().Discover();

Please assist.

Regards
Jolanda

**Comment by mariotoffia** [comment]
do you have any of the docker binaries in the container - such as _docker_, _docker-machine_? it complaints that it cannot find these binaries

Cheers,
Mario

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mariotoffia** [comment]
Since I haven't heard of you for a while I will close this issue now but I can open it again if you still have problems.

Cheers,
 Mario

**Comment by srinathck** [comment]
Hi,
I have a similar issue. 
Running the code from a container and my container doesn't have docker or docker machine installed on it. I would still like to communicate with the host machine from container and use fluentdocker to issue docker-compose commands. Is that possible?

**Comment by HerrMuellerluedenscheid** [comment]
Having the same issue when running on OSX
