### ISSUE TITLE
ComposeUp/ComposeDown fail if the .yml file path/name contains spaces

### ISSUE THREAD

**Issue by rlundy** [mariotoffia/FluentDocker#52]
When running `ComposeUp` or `ComposeDown`, the command fails if the YAML file path/name contains spaces.

```
Commands.Compose.ComposeUp(dockerUri, filePathWithSpacesInName);

Commands.Compose.ComposeDown(dockerUri, composeFile: filePathWithSpacesInName);
```

I think it just needs double-quotes around the file parameter:

```
    public static CommandResponse<IList<string>> ComposeDown(this DockerUri host, [...etc.])
    {
      var args = $"{host.RenderBaseArgs(certificates)}";
      if (!string.IsNullOrEmpty(composeFile))
      {
        args += $" -f {composeFile}";  // <---------- here
      }
```

I think the line noted should be
```
args += $" -f \"{composeFile}\"";
```

(Sorry for no pull request, but even after getting the Postgres container running, I can't get most of the tests to work on my machine, so I wouldn't be able to know whether the changes broke anything.)

**Comment by mariotoffia** [comment]
Neat! ;) But can you do a pull request anyway?

Cheers,
Mario

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rlundy** [comment]
Sure thing!  If you can post a guide to what setup is needed to get all the tests to pass, then once I've got them all passing, I'll be delighted to do a pull request.  😁

**Comment by rlundy** [comment]
OK, FWIW, here's a pull request.

https://github.com/mariotoffia/FluentDocker/pull/53

**Comment by mariotoffia** [comment]
Thanks! I'm curious what fails for the unit tests. Apart for me having docker installed I'm sure I've got no other prereqs…
