### ISSUE TITLE
Hardcoded Windows path seperator.

### ISSUE THREAD

**Issue by bastetfurry** [mariotoffia/FluentDocker#57]
https://github.com/mariotoffia/FluentDocker/blob/415e3f54f499fc6c75cc504788713f598bb4f594/Ductus.FluentDocker/Builders/FileBuilder.cs#L26

Shouldn't that use Path.Combine or at least Path.DirectorySeparatorChar?
Otherwise this is very Windows-centric code.

**Comment by mariotoffia** [comment]
@bastetfurry  It should be resolved now. If you experience any more problem I'll open this issue again.
