### ISSUE TITLE
Error when mounting folder

### ISSUE THREAD

**Issue by lorenzo93** [mariotoffia/FluentDocker#58]
Hi,

Today I started working with `.Mount` to mount folders inside the container.
I'm working in Windows with linux containers (default options)

If I try to mount a directory with a space in the path I get weird errors by the docker deamon. I'm quite sure the problem is a wrong escaping of the string with the path.

Maybe could be better to give the input path as an instance of FileInfo class or to add quotes or escaping characters

**Comment by mariotoffia** [comment]
@lorenzo93 I've checked in and released (https://github.com/mariotoffia/FluentDocker/releases/tag/2.4.0) with (hopefully) a fix of your problem. I've done  a unit test where the mount do have spaces in the path and it works. It takes some time before nuget will be publicly available. 

If you have the time, please report back if it worked for you or not.

Cheers,
 Mario

**Comment by lorenzo93** [comment]
Thank you very much! you were really helpful.

I've updated the library and seems to mount folders correctly!
