### ISSUE TITLE
Connect to Remote Docker Daemon

### ISSUE THREAD

**Issue by lorenzo93** [mariotoffia/FluentDocker#60]
Hi,

It is still me! I'm sorry for so many issues but I'm using really a lot your library and I always have questions :)

I'm creating images from Dockerfile with the example you provided in previous issue and all works correctly.
`            new Ductus.FluentDocker.Builders.Builder()
             .DefineImage("ImageName").ReuseIfAlreadyExists()
             .FromFile("DockerfilePath")
             .Build();`

How can I assure I'm using the right DockerUri? In this command it is not specified the DockerHostService or DockerUri.
I'm asking because I'll need to operate with more than one docker instance, on remote hosts, so I want to create specific images on different hosts.

Thank you for everything :)

**Comment by mariotoffia** [comment]
Hi @lorenzo93 , I've not tried this myself - however I know people have used remote docker on e.g. digital ocean etc. What they do is register the remote docker daemon as a _docker-machine_ (see https://www.kevinkuszyk.com/2016/11/28/connect-your-docker-client-to-a-remote-docker-host/) and use the ```UseMachine()``` and specify the machine name and the fluent API will look this up in the _docker-machine_ registry and use it's _URL_ and _Certificates_ for communication. Please have a go and tell me if you had any success. Otherwise I'll have a go as well.


Cheers,
 Mario

**Comment by mariotoffia** [comment]
@lorenzo93 I have checked in, but not tested or released a remote ssh builder to have a fluent access to remote docker daemons using ssh. You still need to (as descibed in above tutorial link):
* ssh-keygen -t rsa
* ssh-copy-id {username}@{host}
* sudo nano /etc/sudoers (And add the following to the end of the file where {username} is your username on the remote machine: {username}  ALL=(ALL) NOPASSWD:ALL)
* Make sure 2376 port is open on your firewall

Now you can ssh to the machine and communicate with the remote docker daemon. It is now possible to use 
```cs
Hos().UseSsh("ip to remote daemon").Name("name-of-your-connection").Build();
```
Now you have a host that talk to the remote docker daemon. As I said, I haven't tried it yet (have to wait until the weekend to setup this test). If it succeeds I'll make a release this weekend.

Cheers,
 Mario

**Comment by lorenzo93** [comment]
I'm sorry but maybe I misunderstand your first reply.
With current NuGet version (2.4.0) I couldn't find anywhere the `UseMachine()` command.
Here there is an example of what I tried

`            new Ductus.FluentDocker.Builders.Builder().UseMachine()
                .DefineImage(ImageName).ReuseIfAlreadyExists()
                .FromFile(DockerfilePath)
                .Build();`

**Comment by mariotoffia** [comment]
Yes, the 2.4.0 do not have the above builder. I need to test it first. Meanwhile you can if you want instantiate a dockerhost using only a name. This name must match a machine name where you have done the remote configuration. This host will then communicate with the remote docker daemon. I need to setup a remote docker somewhere so I can test my new code before doing a new release, sorry...

Cheers,
 Mario

**Comment by mariotoffia** [comment]
@lorenzo93 I have now tested and committed the code to use one way of accessing remote docker daemons and defining those connections. 

Please use the release 2.5.0 if you want to try it out. There's a new section in the documentation about connecting (and preparing for remote connections) at https://github.com/mariotoffia/FluentDocker#connecting-to-remote-docker-daemons. 

Please note that it will re-use an already existing named connection but if it has to create a new one it will take considerable amount of time!

I would love to get your feedback on this!

Cheers,
 Mario

**Comment by lorenzo93** [comment]
Thank you very much!!!

I'll give you a feedback on Monday (maybe Tuesday) when I'll be at work.

Cheers,
Lorenzo

**Comment by mariotoffia** [comment]
Since I haven't heard from you and I have myself successfully tested this feature both in windows and Linux - I'm closing this issue now. But if you have trouble, please don't hesitate to reply in this thread and I'll open it again.

**Comment by lorenzo93** [comment]
Hi,

as in the other issue I'm sorry for answering so late!
Also this change seems to work perfectly, I didn't test it in all my use cases for lack of time but in the base ones works!

Thank you!

PS is there a way I can offer you a beer? maybe through a donation link. You were very helpful for me and my project and I'd like to say thank you in the proper way! ;)

**Comment by mariotoffia** [comment]
Thanks for the offer! :) Haven't thought about that. I'll think of something - but it will always be free and highly free willingly to donate.

Cheers,
 Mario
