### ISSUE TITLE
Port is never passed as argument in Compose.ComposePort

### ISSUE THREAD

**Issue by olegmoz** [mariotoffia/FluentDocker#61]
Port parameter is always replaced with empty string in Compose.ComposePort method:
`
if (!string.IsNullOrEmpty(privatePortAndProto))
      {
        privatePortAndProto = string.Empty;
      }
`
Please invert the if condition, this bug makes the method unusable right now

**Comment by mariotoffia** [comment]
@olegmoz It is fixed and published as nuget release 2.4.1 **(https://www.nuget.org/packages/Ductus.FluentDocker/2.4.1)** however it will take some amount of time before nuget indexes it and it becomes available for public use (it usually do not take long time).

Cheers,
 Mario

**Comment by olegmoz** [comment]
Thank you!

**Comment by mariotoffia** [comment]
@olegmoz If you like it! Please star it :)
