### ISSUE TITLE
How to manually create a DockerHostService instance

### ISSUE THREAD

**Issue by lorenzo93** [mariotoffia/FluentDocker#64]
Hi Mario,

sorry to still bother you... this time I have a bug found!!!
I'm trying my software on linux (it is all created and executed with .NET Core) and I found a little problem.

I've attached the output of `docker info` [here](https://github.com/mariotoffia/FluentDocker/files/2438141/DockerInfo.txt) so you can have all the informations about my environment.

When I try to get all containers with the code provided below I get an empty list

`DockerHostService host = new DockerHostService("local", true, dockerUri: "npipe://./pipe/docker_engine");
List<IContainerService> allcontainers = c.GetContainers().ToList();`

**Comment by mariotoffia** [comment]
@lorenzo93 Hi, if you are running on a Linux or mac os based system you cannot use a window named pipe. Instead use the unix domain socket. If you try this

```cs
var host = new Hosts().FromMachineName("local");
```
This will communicate with docker machine and give the correct URL to the host.
If you wish to communicate with the native local docker daemon you can do it like this:

```cs
var host = new Hosts().Native();
```
This will give back a valid host if any is present. It will autodetect if it is on Linux, mac, or windows and adjust the _dockerUri_ accordingly. For example on Unix: 
1) Check the environment variable _DOCKER_HOST_ (if found, use it)
2) use unix default _unix:///var/run/docker.sock_

If you really want to instantiate a ```DockerHostService``` yourself either use operating system dependant _URI_ or just pass _null_ and it will autoprobe it. But I strongly suggest using the ```Hosts``` methods to get the hosts.

I hope this will work for you. Please report back if you had any success or failure!

Cheers,
  Mario

**Comment by lorenzo93** [comment]
@mariotoffia neither the frommachinename nor native works. After `new Hosts()` the only function I'm allowed to call is `Discover()`, maybe those functions are private or internal?

**Comment by mariotoffia** [comment]
@lorenzo93 Sorry, it wasn't released. I just just released (https://github.com/mariotoffia/FluentDocker/releases/tag/2.6.0) - it is just waiting for indexing then it will become available.

Is it a native docker or do you have defined a docker machine that you wish to use on your linux host?
If it is the native - you can test to execute this:
```cs
var native = new DockerHostService("native", true, false, null,
          Environment.GetEnvironmentVariable("DOCKER_CERT_PATH");
```

or if it is a machine that you have created or remote daemon (that is registered in docker-machine registry):
```cs
var machine new DockerHostService(name);
```

However when 2.6.0 is indexed on nuget I strongly suggest using the above functions on ```Hosts()```.

Cheers,
 Mario

**Comment by mariotoffia** [comment]
@lorenzo93  I've also installed a Linux so I can dual boot and test my library on a linux to better help.
I've followed the tutorial how to set up and make sure that my user do have access to the docker daemon socket ().

I've tested this program:
```cs
        static void Main(string[] args)
        {
            var hosts = new Hosts().Discover();
            Console.WriteLine($"Number of hosts:{hosts.Count}");
            foreach(var host in hosts)
            {
                Console.WriteLine($"{host.Host} {host.Name} {host.State}");
            }
            Console.WriteLine("Spinning up a postgres and wait for ready state...");
            using (
                var container =
                new Builder().UseContainer()
                    .UseImage("postgres:9.6-alpine")
                    .ExposePort(5432)
                    .WithEnvironment("POSTGRES_PASSWORD=mysecretpassword")
                    .WaitForPort("5432/tcp", 30000 /*30s*/)
                    .Build()
                    .Start())
            {
                var config = container.GetConfiguration(true);
                if (ServiceRunningState.Running == config.State.ToServiceState())
                {
                    Console.WriteLine("Service is running");
                }
                else
                {
                    Console.WriteLine("Failed to start nginx instance...");
                }
            }  
        }
```
And it worked just fine and outputted:
```
Number of hosts:1
unix:///var/run/docker.sock native Running
Spinning up a postgres and wait for ready state...
Service is running

Process finished with exit code 0.
```
The program output denotes that it found one single docker daemon, the local since url _unix:///var/run/docker.sock_ and used that one to spin up a postgres machine.

I hope this helps?

Cheers,
 Mario

**Comment by mariotoffia** [comment]
@lorenzo93 If you need to use sudo? You can in 2.6.1. It supports no sudo, plain sudo without password and sudo with password. Se release notes for 2.6.1.

Cheers,
 Mario

**Comment by mariotoffia** [comment]
@lorenzo93 Any luck with your Linux test?

**Comment by mariotoffia** [comment]
@lorenzo93 Hi, I'm closing this now since I haven't heard anything. I also have tested this and it works for me. If you have any problem, please don't hesitate to open a new or just file the problem in this issue.

Cheers,
 Mario

**Comment by lorenzo93** [comment]
@mariotoffia I'm sorry for anwsering so late, I had a rough week and I didn't have time to properly test this changes.
Using this line of code now everything works like should do.
`var host = new Hosts().Native();`

Thank you very much for your help!
