### ISSUE TITLE
Get PID of running container

### ISSUE THREAD

**Issue by lorenzo93** [mariotoffia/FluentDocker#66]
Hi,

this time it is quite simple, it is possible to get the PID of the container?
With `docker` command it is possible, is there any api on your library?

I'm getting the value like this
`docker inspect --format '{{.State.Pid}}' container_name`

**Comment by mariotoffia** [comment]
That's simple :) - just use the ```Id``` property on the container service and you get the id. For example this unittest in fluentdocker:

```cs
public void BuildAndStartContainerWithKeepContainerWillLeaveContainerInArchve()
    {
      string id;
      using (
        var container =
          new Builder().UseContainer()
            .UseImage("postgres:9.6-alpine")
            .WithEnvironment("POSTGRES_PASSWORD=mysecretpassword")
            .KeepContainer()
            .Build()
            .Start())
      {
        id = container.Id;
        Assert.IsNotNull(id);
      }

      // We shall have the container as stopped by now.
      var cont =
        new Hosts()
          .Discover()
          .Select(host => host.GetContainers().FirstOrDefault(x => x.Id == id))
          .FirstOrDefault(container => null != container);

      Assert.IsNotNull(cont);
      cont.Remove(true);
    }
```
Extracts the id to be used to delete when in stopped mode.

Cheers,
 Mario

**Comment by lorenzo93** [comment]
Thank you very much, I couldn't find the option

Il lun 8 ott 2018, 10:23 Mario Toffia <notifications@github.com> ha scritto:
