### ISSUE TITLE
Start Privileged container

### ISSUE THREAD

**Issue by lorenzo93** [mariotoffia/FluentDocker#68]
Hi,

is there an option to start a container with privileged mode? (--privileged)

**Comment by mariotoffia** [comment]
Yes, If you use e.g. ```_docker.Run(...) you can pass ```ContainerBuildParams``` where it has a ```Privileged``` for example:
```cs
        var cmd = _docker.Run("postgres:9.6-alpine", new ContainerCreateParams
        {
          Privileged = true,
          PortMappings = new[] {"40001:5432"},
          Environment = new[] {"POSTGRES_PASSWORD=mysecretpassword"}
        }, _certificates);
```
In source code, it now (**but not released**) exist a ```IsPrivileged``` on the ```ContainerBuilder``` and with the next release it will also support the _Fluent API_ for privileged containers.

Cheers,
 Mario

**Comment by lorenzo93** [comment]
Thank you, is there a way (with Run) to specify network as `INetworkService` object?
In the fluent API it is possible, or I just need to call the `.Name` on the `INetworkService`?

**Comment by mariotoffia** [comment]
If you set the Network to the name of your network it will attach the container to that network in the ```ContainerCreateParams``` as documented:
```cs
    /// <summary>
    ///   Connect a container to a network
    /// </summary>
    /// <remarks>
    ///   --network
    /// </remarks>
    public string Network { get; set; }
```

Cheers,
 Mario
