### ISSUE TITLE
Container name lost first char

### ISSUE THREAD

**Issue by lorenzo93** [mariotoffia/FluentDocker#69]
Hi Mario,

just creating a container with che method you provided me before (I needed just to Create and not to Start) and I'm having a strange behaviour on the container name.
The container is created with the right name but somehow the variable associated to the name is missing the first char

Cheers,
Lorenzo

```cs
			IContainerService container_x = host.Create("ubuntu", new ContainerCreateParams
			{
				Privileged = true,
				Network = created.Name,
				Name = "container_X",
				Interactive = true,
				Tty = true
			});

			Console.WriteLine(container_x.Name); //printing "ontainer_X"
```

**Comment by mariotoffia** [comment]
I know where this bug resides - I cannot fix it tonight (no charger for my laptop) in meanwhile just add extra char when create until i release 2.6.3

**Comment by lorenzo93** [comment]
No problem!
I already added manually the extra character. I just wanted to inform you
about the bug! :)

Cheers
Lorenzo

Il lun 8 ott 2018, 21:11 Mario Toffia <notifications@github.com> ha scritto:

**Comment by mariotoffia** [comment]
done - will be in next release (around this weekend)
