### ISSUE TITLE
Private Repositories

### ISSUE THREAD

**Issue by davemartindale** [mariotoffia/FluentDocker#71]
Is there a way, using the Fluent code, to use an image from a private repository? 

We're using the Builder().UseContainer().UseImage("imageName") code to pull images but in some cases these are images on private repositories. Ideally we'd like to be able to specify the credentials in our code as opposed to having to do docker login on each machine we want to run this on.

I've looked through the documentation but haven't been able to spot anything although I am a relative novice to docker so may have missed something obvious?

**Comment by mariotoffia** [comment]
Hi, you have not missed anything. It needs to be added! :). I'll try to do next weekend or if you want provide with a PR.

Cheers,
 Mario

**Comment by davemartindale** [comment]
Thanks for the quick response @mariotoffia, this is exactly what I was looking for. 👍

**Comment by mariotoffia** [comment]
@davemartindale  Have you had the possibility to try it out - by compiling the source? otherwise I'll try it out this weekend.

Cheers,
 Mario

**Comment by davemartindale** [comment]
@mariotoffia not yet, I'll let you know if I get chance to test it before then.

**Comment by davemartindale** [comment]
@mariotoffia I've tried this out now and it seems to work well 👍

**Comment by mariotoffia** [comment]
@davemartindale  Nice! I'm packing up a release tonight! Many thanks! :)

**Comment by mariotoffia** [comment]
Published 2.6.4 in nuget and added a release. Hope everything works well!

Cheers,
 Mario
