### ISSUE TITLE
Typo: NetworkBuilder.KeepOnDispse

### ISSUE THREAD

**Issue by TehPers** [mariotoffia/FluentDocker#77]
In v2.6.4, there appears to be a typo in the name of the method `NetworkBuilder.KeepOnDispse`:

```cs
using (var network = new Builder(this._defaultBuilder)
    .UseNetwork("my_network")
    .UseDriver("bridge")
    .KeepOnDispse() // <-- Should be `KeepOnDispose`?
    .Build()) {
    // etc
}

```

**Comment by mariotoffia** [comment]
Hi and thanks for the bug report! I'll fix the typo but keep the old one as well and set it to deprecated this weekend.

Cheers,
 Mario
