### ISSUE TITLE
Prevent Container from Accessing Internet

### ISSUE THREAD

**Issue by StuartFergusonVme** [mariotoffia/FluentDocker#82]
I was wondering if there is a way using your library from preventing a container from sending traffic out over the internet but maintaining support for exposing ports to the host operating system?

I have looked at IsInternal() on the Network builder but this seems to prevent me from exposing ports to the host.

**Comment by mariotoffia** [comment]
Hi @StuartFergusonVme - I haven't stumbled upon this precise setup before. I too get this problem as well. I've done a test case to replicate this behavior and will have a go in coming days to se if can be solved without fiddling with `ip-tables` or alike.

The unittest I've setup:

```cs
      using (var nw = Fd.UseNetwork("unit-test-nw")
                        .IsInternal()
                        .UseDriver("overlay")
                        .IsAttachAble()
                        .Build())
      {
        // docker run alpine ping 10.11.12.13 -c 1 -w 5 -W 5
        using (
          var container =
            Fd.UseContainer()
              .WithName("internal-container")
              .UseImage("alpine")
              .UseNetwork(nw)
              .Command("ping", "1.1.1.1", "-c 1", "-w 5", "-W 5")
              .Build()
              .Start())
        {
          var log = container.Logs().ReadToEnd();
          var ec = container.GetConfiguration(true).State.ExitCode;
          Assert.AreEqual(1, ec);
        }

        using (var container =
          Fd.UseContainer()
            .UseImage("nginx:1.13.6-alpine")
            .ExposePort(80)
            .UseNetwork(nw)
            .WaitForPort("80/tcp", 30000 /*30s*/)
            .Build()
            .Start())
        {
          var response = $"http://{container.ToHostExposedEndpoint("80/tcp")}".Wget().Result;
          Console.WriteLine(response);
        }
      }
    }
```

Cheers,
 Mario

**Comment by mariotoffia** [comment]
@StuartFergusonVme I've asked a collegue of which do this every day and he thinks that, as I stated above, `ip-tables` is the way to go here. I've added the label _help wanted_ to see if any other has some suggestions. I have no current plan to include ip-tables in the library but you may use the [ProcessExecutor](https://github.com/mariotoffia/FluentDocker/blob/master/Ductus.FluentDocker/Executors/ProcessExecutor.cs) "framework" to invoke ip-tables if you want.

It would be interesting to see you solution if you decide to go for `ip-tables`.

Cheers,
 Mario :)

**Comment by StevenBlair123** [comment]
Mario, any advice on how we could run the iptables command in elevated privileges?
We are experimenting with this, and tried to block an IP, but continue to be informed we do not have permission to run the command.

**Comment by mariotoffia** [comment]
How to run it using the `ProcessExecutor` with elevated priviledges? Just use `echo {SudoPassword} | sudo -S <ip-tables binary fq path>` as command to the `ProcessExecutor`. Check the `SetSudo` in the [CommandExtension](https://github.com/mariotoffia/FluentDocker/blob/master/Ductus.FluentDocker/Extensions/CommandExtensions.cs) for how it is done within the library.

The `ProcessExecutor` picks up that a echo or sudo is provided as the first argument and takes appropriate measures.

I hope this was the answer you where looking for.

Cheers,
 Mario

**Comment by mariotoffia** [comment]
@StevenBlair123 The only way of doing this without iptables that I've found is using [whitelist](https://hub.docker.com/r/tecnativa/whitelist/) that is a workaround the --internal issue filed at [moby project](https://github.com/moby/moby/issues/36174).

Cheers,
 Mario

**Comment by StevenBlair123** [comment]
We seem to have a solution working here, but it's still very rough and not production ready.
Unsure if we can graft into the nuget, or whether it needs to reside in our code base (using iptables as suggested)

**Comment by mariotoffia** [comment]
@StevenBlair123 Is it integrated into my codebase or did you do outside? If former, could you please do a PR? otherwise I'm really interested to see your solution.

Cheers,
 Mario

**Comment by StevenBlair123** [comment]
At the moment, it's in our own code base, and discussing internally whether we should try to clean up the code and merge it into your codebase.

Here is the method we are using:

```
        public static ContainerBuilder WithInternalAccessOnly(this ContainerBuilder containerBuilder)
        {
            containerBuilder.UseCapability("NET_ADMIN");
            
            containerBuilder.ExecuteOnRunning("apt-get update",                             
                                              "apt-get -y install iptables",
                                              
                                              // # ALLOW LOOPBACK #                                  
                                              "iptables -A INPUT -i lo -j ACCEPT",
                                              "iptables -A OUTPUT -o lo -j ACCEPT",
                                              
                                              // # BLOCK ALL INCOMING/OUTGOING #
                                              "iptables -P INPUT DROP",
                                              "iptables -P OUTPUT DROP",

                                              // # ALLOW TRAFFIC ON INTERNAL NETWORKS #
                                              "iptables -A INPUT -s 172.17.0.0/8 -j ACCEPT",
                                              "iptables -A INPUT -s 192.168.0.0/16 -j ACCEPT",
                                              "iptables -A OUTPUT -d 172.17.0.0/8 -j ACCEPT",
                                              "iptables -A OUTPUT -d 192.168.0.0/16 -j ACCEPT");

            return containerBuilder;
        }
```
