### ISSUE TITLE
Use docker arguments in FluentAPI or Builder?

### ISSUE THREAD

**Issue by stefanjarina** [mariotoffia/FluentDocker#88]
Hello,

first of all, thank you for this library, it covers almost all my needs.

However, I was wondering if it is possible to somehow specify some docker arguments using Builder or Fluent API?

For example to set a --ulimit argument.

From documentation it is not clear at all, how to add it, if for example I build my container like:

```csharp
var container = new Builder()
                .UseContainer()
                .WithName($"{_configuration.Prefix}-{service.Name}")
                .UseImage(image)
                .UseNetwork(networkName).Build();
```

for example, I am trying to replicate this command:

* When creating Clickhouse `--ulimit` is advised to use

```powershell
docker create --net servers -v clickhouse-data:/var/lib/clickhouse --ulimit nofile=262144:262144 --name clickhouse-server -p 8123:8123 -p 9000:9000 yandex/clickhouse-server:$Version
```

Cheers,
Stefan

**Comment by mariotoffia** [comment]
thanks for the really good description! - I'll try to make it to this weekends release.

cheers,
mario

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mariotoffia** [comment]
@stefanjarina It is in the repo now but I've got a bug that I've fixed that I wanted to be tested before releasing... But now it is possible to write e.g.
```cs
        var container =
          Fd.UseContainer()
            .UseImage("postgres:latest", force: true)
            .UseUlimit(Ulimit.NoFile,2048, 2048)
            .WithEnvironment("POSTGRES_PASSWORD=mysecretpassword")
            .Build()
            .Start()
```

**Comment by stefanjarina** [comment]
@mariotoffia Brilliant! This helps a lot, thanks for implementing it so soon.
