### ISSUE TITLE
Missing reference to logger

### ISSUE THREAD

**Issue by msdeibel** [mariotoffia/FluentDocker#91]
I just cloned the repo to run a container with compose but I'm getting an error when trying to start.

My code
```
using System.IO;
using Ductus.FluentDocker.Builders;
using Ductus.FluentDocker.Model.Common;

namespace ComposeStartPoc
{
    class Program
    {
        static void Main(string[] args)
        {
            var file = Path.Combine(Directory.GetCurrentDirectory(),
                                    (TemplateString)@"C:\path\to\\docker-compose.yml");

            using (var svc = new Builder()
                              .UseContainer()
                              .UseCompose()
                              .FromFile(file)
                              .RemoveOrphans()
                              .Build()
                              .Start())
            {
                System.Threading.Thread.Sleep(120000);

                svc.Stop();
            }
        }
    }
}
```

I get the following exception in line 44 of `Ductus.FluentDocker.Executors.ProcessExecutor`

`System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. `

No inner exception.

VS 2019 says the restoring of dependencies was OK  and the debug build was successful.
In my project I only referenced the `Ductus.FluentDocker.dll` from the `Ductus.fluentDocker\bin\Debug\netstandard2.0` folder

**Comment by mariotoffia** [comment]
@msdeibel Thanks for the bug report - I've never encountered this problem - but to be fair - I've not cloned a clean repo for a while now. I'll check it up!

Cheers,
 Mario

**Comment by mariotoffia** [comment]
@msdeibel I've cloned the repo and **switched view** to _FluentDocker.sln_. I did set the Tests project as startup project and uncommented `RunContainer()` in the `Main` function. Hit _F5_ and got the following output (worked just fine in my case):

```
Number of hosts:3
npipe:////./pipe/docker_engine native Running
tcp://255.255.255.255:2376/ test-machine Running
tcp://192.168.1.113:2376/ wifi-test Running
Spinning up a postgres and wait for ready state...
Service is running

C:\Program Files\dotnet\dotnet.exe (process 5652) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .
```

Can you try the same and see what's happening at your end?

Cheers,
 Mario

**Comment by mariotoffia** [comment]
@msdeibel Since I haven't hear from you for a while I'd guess everything is ok? I'll close this ticket for now - if the problem still persiste just open the issue again.

Cheers,
 Mario

**Comment by msdeibel** [comment]
I tried your steps on my end. I didn't get the ouput but the operation finished with exit code 0, so I guess the test is OK. I also tried to used the compiled lib in my project, but encountered anouther error. I'll open a separate issue for that.
