### ISSUE TITLE
WaitForPort hangs forever.

### ISSUE THREAD

**Issue by maurovisintin** [mariotoffia/FluentDocker#92]
Running the following snippet:
```cs
protected override Task OnStart(CancellationToken cancellationToken)
        {
            try
            {
                this.Logger.LogInformation("Starting mailhog container. This may take a few minutes if the image is not in local cache.");

                this.containerService = new Builder()
                    .UseContainer()
                    .WithName("profiles-smtp-server")
                    .UseImage("mailhog/mailhog:latest")
                    .ReuseIfExists()
                    .ExposePort(5011, 8025)
                    .ExposePort(1025) 
                    .WaitForPort("8025/tcp", 5000)
                    .Build();

                this.containerService.Start();
            }
            catch (FluentDockerException ex) when (ex.Message.Contains("Error response from daemon: Conflict"))
            {
                this.Logger.LogInformation("Seq container already running.");
            }
            this.Logger.LogInformation("mailhog started");
            return Task.CompletedTask;
        }
```
I can see the log info for the container starting, but never get to the "started" message.
The process waits indefinitely for the port.

After some minutes I get:
```
[16:23:16 FTL] Host terminated unexpectedly
Ductus.FluentDocker.Common.FluentDockerException: Timeout waiting for service at = 31.199.53.9 port = 5011 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Operation timed out [::ffff:31.199.53.9]:5011
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at Ductus.FluentDocker.Services.Extensions.NetworkExtensions.WaitForPort(IPEndPoint endpoint, Int64 millisTimeout)
   --- End of inner exception stack trace ---
```
I see the container running
```
121509a22f7d        mailhog/mailhog:latest   "MailHog"                About a minute ago   Up About a minute      0.0.0.0:32774->1025/tcp, 0.0.0.0:5011->8025/tcp                                                                                                                                 profiles-smtp-server
```
and I can successfully access to mailhog ui at `http://localhost:5011/`

**Comment by mariotoffia** [comment]
@maurovisintin Do you have some sort of firewall rules or otherwise routing table that is not correct?  I've wrote a unit test to simulate your setup on my local as follows

```cs
 [TestMethod]
    public void Issue92()
    {
      using (var c = Fd.UseContainer()
        .WithName("profiles-smtp-server")
        .UseImage("mailhog/mailhog:latest")
        .ReuseIfExists()
        .ExposePort(5011, 8025)
        .ExposePort(1025)
        .WaitForPort("8025/tcp", TimeSpan.FromSeconds(30))
        .Build())
      {
        c.Start();
        var response = $"http://{c.ToHostExposedEndpoint("8025/tcp")}/".Wget().Result;
        IsTrue(response.IndexOf("<title>MailHog</title>", StringComparison.Ordinal) != -1);
      }
    }
```

and it works fine. Can you do a `curl 31.199.53:9:5011` successfully (replace IP with your current IP)?

**Comment by maurovisintin** [comment]
As I mentioned in the issue, I can successfully access to `http://localhost:5011/` both from chrome and curl. But the process never gets past  `c.Start();`

**Comment by mariotoffia** [comment]
Yes, but not on your IP address  - can you try that since fluentdocker resolves the IP address and do not use localhost. Can you, please, try to access using the IP address from chrome instead and see if you get the same behaviour?

Cheers,
 Mario

**Comment by maurovisintin** [comment]
I tried with my Private IP Address, `http://192.168.1.215:5011/` and still works as expected.

**Comment by mariotoffia** [comment]
Hmm... do your computer have both a private and public ip address? It seems that the framwrok choose your public in that case `31.199.53.9`and I'm guessing that it is under firewall.. It this is the case, I'll need to add the checks and always strive to use private ones...

**Comment by maurovisintin** [comment]
Actually `31.199.53.9` is neither my private or public IP, trying to understand why is it looking for that IP

**Comment by mariotoffia** [comment]
@maurovisintin It resolves your address using the container network configuration - so it is the address of the container (doing docker inspect and checks the network section of the container).

**Comment by mariotoffia** [comment]
@maurovisintin Do you have the ability to clone the master and test the extension on ```WaitForPort``` to see if this solves your issue?

Cheers,
 Mario

**Comment by mariotoffia** [comment]
@maurovisintin I've pushed [release 2.7.0](https://github.com/mariotoffia/FluentDocker/releases/tag/2.7.0) to nuget - no need to clone. However, if you find the root cause of the problem I would really like to have that feedback and how you have setup your networking.

It may take some time before _2.7.0_ is indexed/published on [nuget](https://www.nuget.org/packages/Ductus.FluentDocker)

Cheers,
 Mario

**Comment by maurovisintin** [comment]
It works, thanks for the support!
