### ISSUE TITLE
[Windows] Can I run fluentdocker inside container without client binary?

### ISSUE THREAD

**Issue by srinathck** [mariotoffia/FluentDocker#93]
So I am trying to discover hosts from a Docker Container and When I debug the container using VS2017, I get this error.

```
| $exception | {System.TypeInitializationException: The type initializer for 'Ductus.FluentDocker.Extensions.CommandExtensions' threw an exception. ---> Ductus.FluentDocker.Common.FluentDockerException: Failed to find docker client binary - please add it to your path    at Ductus.FluentDocker.Extensions.Utils.DockerBinariesResolver..ctor(SudoMechanism sudo, String password, String[] paths)    at Ductus.FluentDocker.Extensions.CommandExtensions..cctor()    --- End of inner exception stack trace ---    at Ductus.FluentDocker.Extensions.CommandExtensions.IsEmulatedNative()    at Ductus.FluentDocker.Services.Hosts.Native()    at Ductus.FluentDocker.Services.Hosts.Discover(Boolean preferNative)    at ExampleDao.ConnectToDocker()  at Program.<>c__DisplayClass2_0.<Main>b__0() in E:\DockerComposeCSharp\Program.cs:line 39    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)} | System.TypeInitializationException
```

When I run the same code regularly on my local machine without a container, It works as expected. I want to connect to a Docker client on host machine running the code from an actual Docker container. Can FluentDocker do that?

**Comment by mariotoffia** [comment]
@srinathck Do you have the docker binary in your _Docker_ container? In 2.x it is a neccity and therefore you have add that in a _Dockerfile_ (derive from the container you want to execute and include docker client binary). 

In _4.0_ I plan to have a driver model (Issue #55) and include a HTTP(s) based one so it is possible to communicate without having the _docker_ binaries installed on the machine.

I hope this clarifies your problem?

Cheers,
 Mario

**Comment by srinathck** [comment]
Okay, I can do copy a file using my Dockerfile.
Can you please guide me what binary I should be copying exactly, Where should it be in the container  and where I can find it?

**Comment by mariotoffia** [comment]
Do a google for example [this](https://forums.docker.com/t/how-can-i-run-docker-command-inside-a-docker-container/337) or [this](https://github.com/nathanielc/docker-client) may apply?

Cheers,
 Mario

**Comment by srinathck** [comment]
Okay. You meant for me to install docker client in container. I will do that and let you know if that works. Thank you!

**Comment by mariotoffia** [comment]
@srinathck How did it go?

**Comment by mariotoffia** [comment]
@srinathck I hope everything has gone well with installing docker client binary in the container. I'm closing this ticket now but would like to hear how it did go! :)

Cheers,
 Mario

**Comment by srinathck** [comment]
So, I have tried a bunch of different ways to install Docker CLI on Nanoserver and found out I cannot do that on NanoServer based windows containers (Because of lack of required features like powershell etc.,). I am trying to use the one with Powershell installed in it so I can run docker cli via powershell. 

P.S: All the examples I found online were for Linux containers which is actually fairly simple. But for windows host and windows based containers, It is a little difficult. 

I will try this using a ServerCore Image as base and let you know how it goes. Thanks

**Comment by srinathck** [comment]
I have installed the docker cli on a ServerCore Base image and It went smooth.
But while running a sample console application to check if it can communicate with docker on the host. I see it found a host. 
However, it wasn't able to get the container list/issue compose commands. While it works completely fine from the local machine It doesn't do the same from containers.
Sample Code I am using to test FluentDocker
`        static void Main()
        {
            try
            {
                var hosts = new Hosts().Discover();
                var docker = hosts.FirstOrDefault(x => x.IsNative) ?? hosts.FirstOrDefault(x => x.Name == "default");
                Console.WriteLine($"Docker host: {docker?.Host.Host}, {docker?.Host.AbsolutePath}, {docker?.Host.AbsoluteUri}");
                var containers = docker?.GetContainers();
                Console.WriteLine($"Number of containers: {containers?.Count}");
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
        }`
**Output on Local Machine would be**:
`Docker host: ., /pipe/docker_engine, npipe://./pipe/docker_engine
Number of containers: 8`

**Same code Output on Container**:
`Docker host: ., /pipe/docker_engine, npipe://./pipe/docker_engine
Number of containers: 0`

**Comment by srinathck** [comment]
I was expecting the output to be same on Local machine as well as from Container. Where it clearly is not. I have 8 containers running in Docker. Can you please let me know if i am doing something wrong here. Thanks

**Comment by mariotoffia** [comment]
Hmmm it Will use the containers pipe it must be a Wayne of mounting the pipe to the host pipe the same Way as with linux container needs to mount the domain socket in order to communicate with the host daemon.

**Comment by mariotoffia** [comment]
You can mount the named pipes in same manner as with linux unix domain socket. I haven't tried it but you can have a go and see if it works for you. Use the `-v \\.\pipe\docker_engine:\\.\pipe\docker_engine` as volume mount. In theory it shall mount the host named pipe into the containers named pipe and it _should_ work. Seems to been a [issue](https://github.com/moby/moby/issues/36562) back in 2018 but may been resolved since used nowadays.

Can you have a go and let me know how it went? I might add this as a _API_ call e.g. `MountHostSocket()` so it will be easy to do this...

Cheers,
 Mario

**Comment by srinathck** [comment]
That worked perfect. I just had to run the container with volume mount bind `-v \\.\pipe\docker_engine:\\.\pipe\docker_engine`
Now the Output shows the correct number of Containers:
`Docker host: ., /pipe/docker_engine, npipe://./pipe/docker_engine`
`Number of containers: 6`

**Comment by srinathck** [comment]
So, Here is what I am trying to do now. I am trying to compose up a few containers from within this Docker container. 
```csharp
 var response = docker?.Host.ComposeUp(docker.Host.AbsoluteUri, false, false, false, false, null, false, false, null, null, Environment.CurrentDirectory + "\\docker-compose.deploy.yml");
```
The compose file creates a Windows Container in docker.
But When I try and run the code from a container, I get this error: 
`Docker host: ., /pipe/docker_engine, npipe://./pipe/docker_engine`
`Number of containers: 6`
`C:\DockerCliRemoteTest\DockerCliRemoteTest\bin\Debug\netcoreapp2.1\docker-compose.deploy.yml`
`System.NullReferenceException: Object reference not set to an instance of an object.
   at Ductus.FluentDocker.Extensions.CommandExtensions.ResolveBinary(String dockerCommand, Boolean preferMachine, Boolean forceResolve)
   at Ductus.FluentDocker.Commands.Compose.ComposeUp(DockerUri host, String altProjectName, Boolean forceRecreate, Boolean noRecreate, Boolean dontBuild, Boolean buildBeforeCreate, Nullable`1 timeout, Boolean removeOphans, Boolean useCol
or, String[] services, ICertificatePaths certificates, String[] composeFile)
   at DockerCliRemoteTest.Program.Main() in C:\DockerCliRemoteTest\DockerCliRemoteTest\Program.cs:line 22`

FYI, My docker daemon is TLS secured. Does that have anything to do with this error?
Should I be passing in the Certificates as a parameters to the ComposeUp()

**Comment by mariotoffia** [comment]
It seems that you don't have _docker-compose_ in your container, can that be right?

**Comment by srinathck** [comment]
Oh yeah. That's right. I can issue docker commands but not docker-compose. I will check if there is a way I can install docker-compose. I will let you know if I figure out a way of doing that let me know if you know a better way to install docker-compose on containers. Thank you!

**Comment by srinathck** [comment]
Okay. Now I installed docker compose as mentioned here. https://docs.docker.com/compose/install/
But When I try to ComposeUp the container. It throws this error.
`
Ductus.FluentDocker.Common.FluentDockerException: Could not start composite service System.Collections.Generic.List`1[System.String] - result: Couldn't connect to Docker daemon. You might need to start Docker for Windows.
   at Ductus.FluentDocker.Services.Impl.DockerComposeCompositeService.Start()
   at Ductus.FluentDocker.Services.Impl.DockerComposeCompositeService.Ductus.FluentDocker.Services.ICompositeService.Start()
   at DockerCliRemoteTest.Program.Main() in C:\DockerCliRemoteTest\DockerCliRemoteTest\Program.cs:line 42
`

**Comment by mariotoffia** [comment]
@srinathck  - Do you have a _Dockerfile_ or a script to fire up a windows container containing docker.exe and docker-compose.exe that I can use to debug this issue?

Cheers,
 Mario

**Comment by srinathck** [comment]
@mariotoffia 
This is how my sample project looks. It is a console app and has a (Hello-World) docker-compose.yml file.
![image](https://user-images.githubusercontent.com/26442180/63192213-2e581b00-c030-11e9-8ecf-68d51fc7a462.png)
Docker-Compose file to Compose up
![image](https://user-images.githubusercontent.com/26442180/63192248-3fa12780-c030-11e9-80c2-52f173f32c16.png)
Program.cs file code
```csharp
using System;
using System.Linq;
using Ductus.FluentDocker.Commands;
using Ductus.FluentDocker.Services;

namespace DockerCliRemoteTest
{
    class Program
    {
        static void Main()
        {
            try
            {
                var hosts = new Hosts().Discover();
                var docker = hosts.FirstOrDefault(x => x.IsNative) ?? hosts.FirstOrDefault(x => x.Name == "default");
                Console.WriteLine($"Docker host: {docker?.Host.Host}, {docker?.Host.AbsolutePath}, {docker?.Host.AbsoluteUri}");
                var containers = docker?.GetContainers();
                Console.WriteLine(docker?.Host.Host);
                Console.WriteLine($"Number of containers: {containers?.Count}");
                Console.WriteLine(Environment.CurrentDirectory + "\\docker-compose.yml");
                var response = docker?.Host.ComposeUp(docker.Host.AbsoluteUri, false, false, false, false, null, false, false, null, null, Environment.CurrentDirectory + "\\docker-compose.yml");
                if (response != null && response.Success)
                {
                    Console.WriteLine("Yes. It worked!");
                    foreach (var str in response.Log)
                    {
                        Console.WriteLine(str);
                    }
                }
                else
                {
                    Console.WriteLine(response?.Error);
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
        }
    }
}
```
Here is the DockerFile.
```yml
FROM mcr.microsoft.com/windows/servercore:ltsc2019 AS base
WORKDIR /src
USER ContainerAdministrator 
# Install Dotnet
ENV DOTNET_SDK_VERSION 2.1.403
RUN powershell Invoke-WebRequest -OutFile dotnet.zip https://dotnetcli.blob.core.windows.net/dotnet/Sdk/$Env:DOTNET_SDK_VERSION/dotnet-sdk-$Env:DOTNET_SDK_VERSION-win-x64.zip
RUN powershell Expand-Archive dotnet.zip -DestinationPath 'C:\Program Files\dotnet'
RUN powershell Remove-Item -Force dotnet.zip
RUN setx /M PATH "%PATH%;C:\Program Files\dotnet"
# Install Nuget and Docker
RUN powershell Install-PackageProvider NuGet -Force;
RUN powershell Install-Module DockerMsftProvider -Force; exit 0
RUN powershell Install-Package Docker -ProviderName DockerMsftProvider -Force; exit 0
# Install Docker Compose
RUN powershell [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; exit 0
RUN powershell Invoke-WebRequest "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Windows-x86_64.exe" -UseBasicParsing -OutFile $Env:ProgramFiles\Docker\docker-compose.exe

WORKDIR /app

FROM microsoft/dotnet:2.1-sdk-nanoserver-1803 AS build
WORKDIR /source
COPY . DockerCliRemoteTest/

RUN dotnet restore DockerCliRemoteTest/DockerCliRemoteTest.csproj
COPY . .

WORKDIR /source/DockerCliRemoteTest
RUN dotnet build DockerCliRemoteTest.csproj -c Release -r win-x64 -o /app

FROM build AS publish
RUN dotnet publish DockerCliRemoteTest.csproj -c Release -r win-x64 -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "DockerCliRemoteTest.dll"]
```

Powershell Commands:
`PS ProjectRootFolder>docker build -t dockercliremotetest .`
`docker run -v \\.\pipe\docker_engine:\\.\pipe\docker_engine dockercliremotetest:latest`

Returned Output:
`Docker host: ., /pipe/docker_engine, npipe://./pipe/docker_engine
.
Number of containers: 7
C:\app\docker-compose.yml
Couldn't connect to Docker daemon. You might need to start Docker for Windows.`

**Comment by mariotoffia** [comment]
@srinathck I've reported this on docker-compose git repo since it does not make sense - the docker compose do not correctly resolve the mounted named pipe as I can see it. Let's see if they respond.

**Comment by mariotoffia** [comment]
@srinathck It seems to be others having the exact same problem.

**Comment by srinathck** [comment]
Thanks for following up @mariotoffia I wish they at least responded or assigned the issue by now.

**Comment by srinathck** [comment]
Do you think there are any other Alternatives to what I want to achieve? I just need to be able to Docker-Compose up and down from inside the container. 

Thanks for all your help.

**Comment by mariotoffia** [comment]
Hi and sorry for a short answer - will update when I'm back from business trip.

In short use the docker daemon unsafe url (settings) and set DOCKER_HOST as accordingly (as std remote daemon)

Cheers,
 Mario

**Comment by mariotoffia** [comment]
@srinathck They have finally solved it! :) -  It will come on next release so I'll close this issue now.
