### ISSUE TITLE
Is possible to run a command on a running container? 

### ISSUE THREAD

**Issue by adixia** [mariotoffia/FluentDocker#99]
Hi, 
With FluentDocker is possible to run a command on a specific container?
e.g.
I would like to run a script on my running container in this way: 

`docker exec -t "my_container" "some command to run the script"`

Thanks in advance

**Comment by mariotoffia** [comment]
You can do a execute using the container id since everything is centered around docker daemon uri, certificates (if any), and the full container id.

**Comment by adixia** [comment]
Could you provide an example of the correct way to di It with fluente docker? Thanks

**Comment by mariotoffia** [comment]
Use this as prototype:
```cs
        using (var c = Fd.UseContainer().UseImage("<your-image>").Build().Start())
        {
           c.DockerHost.Execute(c.Id, "command and args", c.Certificates);
        }
```

I've added (will come in next release) a extension so now it is possible to write a short form of the `Execute` command.
```cs
        using (var c = Fd.UseContainer().UseImage("<your-image>").Build().Start())
        {
           c.Execute("command and args");
        }
```

Cheers,
 Mario

**Comment by mariotoffia** [comment]
If it doesn't work please just open the Issue again.

Cheers,
 Mario
